### ISSUE TITLE
[📍] Assign performance bug to the largest bad regression

### ISSUE THREAD

**Issue by npm1** [catapult-project/catapult#4564] opened 2018-07-23 15:13 UTC
Currently, Pinpoint tests the patches and looks for significant differences. Then I think it assigns the bug to the owner of the latest patch causing a difference. It doesn't even consider whether it's a good difference (move towards better number) or a bad difference (move towards worse number). I propose it should instead assign to the owner of the patch causing the worst bad difference. Or at the very least to the owner of the latest patch that causes a bad difference. In this example, it was assigned to a patch with a good difference:

https://bugs.chromium.org/p/chromium/issues/detail?id=866084#c3

**Comment by simonhatch** [comment] 2018-07-23 15:22
Dupe of #4123

**Closed by simonhatch** 2018-07-23 15:22 UTC
