### ISSUE TITLE
Overlapping associated events for Response and Animate IRs

### ISSUE THREAD

**Issue by dj2** [catapult-project/catapult#1431] opened 2015-09-02 15:14 UTC
Looking at [1] there are overlapping Response and Animate IRs in about the middle of the trace. This, I believe is when I briefly tapped as the page looked visually complete.

I'm not sure what caused the Animation but it looks like the associated events for the two IRs are highly overlapping which seemed odd.

Steps to generate trace:
1- Load cnn.com
2- Tap when page looks visually loaded.
3- Slight scroll when page load indicator shows loading is complete.

Device:
Android 40.0.2214.89 (stock chrome on device)

[1] https://drive.google.com/file/d/0BwBaQQ4lL3m2UHpDNjVwUGVRejQ/view?usp=sharing
[2] https://drive.google.com/file/d/0BwBaQQ4lL3m2YVVnUFZEczRlUjA/view?usp=sharing
[3] https://drive.google.com/file/d/0BwBaQQ4lL3m2UHpDNjVwUGVRejQ/view?usp=sharing

**Comment by dj2** [comment] 2015-09-02 15:14
@benshayden @philippebeaudoin

**Comment by dj2** [comment] 2015-09-02 15:38
I did a trace with Android 44.0.2403.133 and I see the same behaviour where the associated events cover the entire timeline, not just the portion under the Response.

**Comment by dj2** [comment] 2015-09-02 15:45
This looks like it's also happening in 44.0.2403.133 [1]. The Response and Animate don't overlap, but they appear to have overlapping associated events.

[1] https://drive.google.com/open?id=0BwBaQQ4lL3m2dTQ5TTBXeWRDblE (shared with @chromium)

**Comment by benshayden** [comment] 2015-09-02 16:10
I still need to look at it, but associated events are not necessarily disjoint between Responses and Animations. Associated InputLatencyAsyncSlices should be disjoint, but occasionally some kinds of slices will have multiple in-flows.

**Comment by benshayden** [comment] 2015-09-02 20:53
It's a Touch Animation, caused by two TouchMove and a TouchEnd ILASs. The handleTouchEvents() state machine thinks it's a drag gesture, in case there isn't a Scroll event for some reason. It doesn't know that there's an overlapping Tap, which wouldn't happen if it were actually a drag gesture. It looks like these ILASs should be merged into the Tap Response.
I could add a post-processor method that looks for non-Scroll non-Pinch Touch-only Animations that overlap a Tap Response and merge them into the Response. That would be very specific to this case, but it would minimize the chances of creating more weird edge cases like this.

**Closed** 2015-09-08 17:36 UTC
Labels: Bug, Perf Insights, RAIL
