### ISSUE TITLE
Dashboard cannot handles memory 's tbmv2 metrics properly

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2286] opened 2016-04-28 14:24 UTC
According to @perezju:
- Sometimes, the dropdown to select a metric does not load (as happened to Petr)
- When it loads, auto-complete seems somewhat broken, for example typing "overall" or "pss" shows nothing, I had to almost type in its entirety "memory:chrome:all:vmstats:overall:pss_avg".
- Sometimes graphs end up with the error "Failed to fetch graph data", even if the chart was already shown.

I'm guessing this could be more of an issue that we're sending lots and lots of metrics? (for every metric now we end up sending _std, _avg, _sum, etc..)

(Context: https://bugs.chromium.org/p/chromium/issues/detail?id=606698#c14)

@petrcermak @perezju

**Comment by nedn** [comment] 2016-04-28 14:25
I assign this bug to Annie for triaging.

**Comment by anniesullie** [comment] 2016-05-02 19:28
I looked into this, it's definitely an issue with lots and lots of metrics.
* I uploaded https://codereview.chromium.org/1939823003 for the "overall" showing nothing
* The menus sometimes don't show up because we are trying to cache the query result, and the query result is too large. I added a workaround in the code review so that we don't see errors to my CL, but it needs a real fix in #2305 in order to make this fast.

**Comment by simonhatch** [comment] 2017-02-14 03:38
Is this still happening? It's pretty old, maybe we can close it out? Just landed a fix today that should make initial metric dropdown loading faster, believe the layered_cache fallback to stored_object fixes the caching issue, I can't repro the autocomplete issue and haven't seen the failed to fetch graph data.

**Comment by perezju** [comment] 2017-02-14 09:48
Things are in a much better shape now, but we would also welcome some improvements:

- Autocomplete is not very useful for memory metrics, filed #3212 with examples.
- The dropdown to select a metric takes a long time to load (~ 3 seconds on some tries I did now). It's not terrible, and we've learned to live with it, but we would be very happy with any improvements there.

**Comment by anniesullie** [comment] 2017-02-14 14:09
Since the remaining bug is the dropdown taking a long time to load, I'm going to close this as a duplicate of #2642 which @eakuefner is actively working on.

**Closed by anniesullie** 2017-02-14 14:09 UTC
Labels: P1, Perf Dashboard
