### ISSUE TITLE
Triaged alerts page gives Internal Server Error

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#1397] opened 2015-08-29 02:39 UTC
https://chromeperf.appspot.com/alerts?triaged=true

Internal Server Error

The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-a909fea7.386690077332365433/dashboard/alerts.py", line 49, in get
    'stoppage_alert_list': json.dumps(StoppageAlertDicts(stoppage_alerts)),
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-a909fea7.386690077332365433/dashboard/alerts.py", line 122, in StoppageAlertDicts
    return [_GetStoppageAlertDict(a) for a in stoppage_alerts]
  File "/base/data/home/apps/s~chromeperf/clean-qyearsley-a909fea7.386690077332365433/dashboard/alerts.py", line 152, in _GetStoppageAlertDict
    'last_row_date': str(stoppage_alert_entity.last_row_date.date()),
AttributeError: 'NoneType' object has no attribute 'date'

**Comment by qyearsley** [comment] 2015-08-29 19:54
Duplicate of #1377; for now I'll log errors and show N/A in the UI for stoppage alerts that have now last row date. I believe that this should only happen for stoppage alerts whose associated row has been moved or deleted; the underlying issue is that migrate_test_names needs to be updated to move stoppage alerts too.

**Closed by qyearsley** 2015-08-29 19:54 UTC
Labels: Perf Dashboard
