### ISSUE TITLE
[📍] Pinpoint figured out that I caused a regression but then said that it failed

### ISSUE THREAD

**Issue by CalebRouleau** [catapult-project/catapult#4062] opened 2017-11-30 00:56 UTC
See https://pinpoint-dot-chromeperf.appspot.com/job/14b10040040000. I would copy the error stack trace in here, but the pinpoint UI makes that extremely difficult to do.

**Comment by CalebRouleau** [comment] 2017-11-30 17:23
Here's another example: https://pinpoint-dot-chromeperf.appspot.com/job/128aba90040000

**Comment by simonhatch** [comment] 2017-11-30 17:32
Managed to pull the exception out manually:


```

Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a1422259.405826798746588903/dashboard/pinpoint/models/job.py", line 202, in Run
    self.state.Explore()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a1422259.405826798746588903/dashboard/pinpoint/models/job.py", line 315, in Explore
    midpoint = change_module.Change.Midpoint(change_a, change_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a1422259.405826798746588903/dashboard/pinpoint/models/change/change.py", line 117, in Midpoint
    commits_midpoint = _FindMidpoints(commits_a, commits_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a1422259.405826798746588903/dashboard/pinpoint/models/change/change.py", line 200, in _FindMidpoints
    deps_a = commit_a.Deps()
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a1422259.405826798746588903/dashboard/pinpoint/models/change/commit.py", line 75, in Deps
    add_if_missing=True)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a1422259.405826798746588903/dashboard/pinpoint/models/change/repository.py", line 66, in Repository
    return _AddRepository(url)
  File "/base/data/home/apps/s~chromeperf/pinpoint:dev-simonhatch-a1422259.405826798746588903/dashboard/pinpoint/models/change/repository.py", line 87, in _AddRepository
    'Datastore: %s: %s' % (name, url))
AssertionError: Attempted to add a repository that's already in the Datastore: custom-tabs-client: https://chromium.googlesource.com/custom-tabs-client

```

I agree it could be easier to pull the exception text, I'll file an issue for that.

**Comment by dave-2** [comment] 2017-11-30 19:24
Duplicate of #3921

**Closed by dave-2** 2017-11-30 19:24 UTC
Labels: Bisect
