### ISSUE TITLE
Pinpoint - Error adding freetype2

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3994] opened 2017-10-20 21:27 UTC
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-275b4a01.404782637659435208/dashboard/pinpoint/models/job.py", line 201, in Run
    self.state.Explore()
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-275b4a01.404782637659435208/dashboard/pinpoint/models/job.py", line 308, in Explore
    midpoint = change_module.Change.Midpoint(change_a, change_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-275b4a01.404782637659435208/dashboard/pinpoint/models/change/change.py", line 117, in Midpoint
    commits_midpoint = _FindMidpoints(commits_a, commits_b)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-275b4a01.404782637659435208/dashboard/pinpoint/models/change/change.py", line 200, in _FindMidpoints
    deps_a = commit_a.Deps()
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-275b4a01.404782637659435208/dashboard/pinpoint/models/change/commit.py", line 75, in Deps
    add_if_missing=True)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-275b4a01.404782637659435208/dashboard/pinpoint/models/change/repository.py", line 66, in Repository
    return _AddRepository(url)
  File "/base/data/home/apps/s~chromeperf/pinpoint:clean-dtu-275b4a01.404782637659435208/dashboard/pinpoint/models/change/repository.py", line 87, in _AddRepository
    'Datastore: %s: %s' % (name, url))
AssertionError: Attempted to add a repository that's already in the Datastore: freetype2: https://skia.googlesource.com/third_party/freetype2

From: https://pinpoint-dot-chromeperf.appspot.com/job/149ce813780000

**Comment by dave-2** [comment] 2017-11-09 21:51
Duplicate of #3921

**Closed by dave-2** 2017-11-09 21:51 UTC
Labels: Bisect
