### ISSUE TITLE
Perf Dashboard: Cannot triage because "something went wrong" when logging in

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2525] opened 2016-07-21 14:49 UTC
Chrome version: 51.0.2704.79 (Linux)
URL: https://dev-sullivan-74e2605e-dot-chromeperf.appspot.com/alerts?sheriff=System%20Health%20Perf%20Sheriff&sortby=end_revision&sortdirection=down

Repro steps:
1. Go to https://dev-sullivan-74e2605e-dot-chromeperf.appspot.com/alerts?sheriff=System%20Health%20Perf%20Sheriff&sortby=end_revision&sortdirection=down
2. Select the first alert.
3. Click on "TRIAGE".
4. Click on "NEW BUG" or "EXISTING BUGS".
5. Select any account to login.
6. The pop-up shows a "Something went wrong" page.

I then reloaded the page and the login was not required anymore (the page for submitting a new bug was displayed after clicking "NEW BUG").

**Comment by anniesullie** [comment] 2016-07-27 12:49
We can't reproduce this, closing but will open again if we see it.

**Closed by anniesullie** 2016-07-27 12:49 UTC
Labels: Perf Dashboard, Polymer 1.0 Migration
