### ISSUE TITLE
Assocated events for response look incorrect.

### ISSUE THREAD

**Issue by dj2** [catapult-project/catapult#1428] opened 2015-09-02 14:51 UTC
For the trace [1] performed the following steps:

1- Load cnn.com.
2- When the page looked complete tapped once.
3- When the progress indicator showed the page was done scrolled slightly.

Looking at the first response [2] you can see that we have events associated through the entire timeline instead of just under the response. We also have something what looks like hundreds of messages bouncing from the IO thread to the Compositor?

Note, this trace was recorded on and Android device running 40.0.2214.89.

[1] https://drive.google.com/open?id=0BwBaQQ4lL3m2M0h4cWJXQWhrbm8
[2] https://drive.google.com/open?id=0BwBaQQ4lL3m2eEJBTTctNXR3OXM

**Comment by dj2** [comment] 2015-09-02 14:52
@philippebeaudoin @benshayden 

I'm going to see if I can get a newer Chrome on the device, but this is the one that came stock which is why it's so old. I'm not sure what we want to do around these kinds of devices. It feels like we have to make sure the IRs work correctly because this is what will be coming from the field.

Is your preference to see me record on the stock Chrome or to see if I can get a newer Canary?

**Comment by dj2** [comment] 2015-09-02 15:44
I did a trace with Android 44.0.2403.133 and I see the same behaviour where the associated events cover the entire timeline, not just the portion under the Response.

**Comment by benshayden** [comment] 2015-09-02 19:10
It's the same root cause as #1263, but the offending slices are titled "overhead". So maybe ILAS needs to ignore slices named "overhead" when deciding what is a single hierarchy? Or can we get rid of those "overhead" slices?

**Comment by dj2** [comment] 2015-09-02 19:47
The overhead slices come from their own category tracing.overhead? (I think). But, you can't count on them not being there.

I'm not sure what ILAS means? I'd assume the overhead slices will appear at the bottom of the slice tree, but haven't looked too closely.

**Comment by benshayden** [comment] 2015-09-02 19:57
Sorry, ILAS = InputLatencyAsyncSlice.
Until now, I'd thought that overhead slices would not span separate tasks, which joins them into larger hierarchies. If that's an expected thing for overhead slices to do, then I guess I'll need to make ILAS ignore them when collecting slices into hierarchies. That's entirely feasible, it just seemed like the kind of special case that you would think is gross.

**Comment by dj2** [comment] 2015-09-02 20:11
Overhead itself is a special case (assuming it's the one I'm thinking of). It's the overhead of tracing itself. I think if you click on it the category is like tracing.overhead or something like that?

**Comment by benshayden** [comment] 2015-09-11 22:07
It looks like my fix for #1263 will also fix this.

**Comment by benshayden** [comment] 2015-09-15 23:36
Nat suggested re-thinking the fix for this and #1263 .
The overhead slices in CrBrowserMain in that trace look broken. (The category is trace_event_overhead for posterity.)
One overhead slice starts at 12,117ms and runs for 1,135ms wall, and -3ms cpuSelfTime.
The next overhead slice starts at 12,178ms, runs for 1465ms wall, and -117ms cpuSelfTime.
These overhead slices overlap both in time and in the same track in the TrackView. The negative cpuSelfTime also looks fishy.
There are also several overhead slices directly under those two, some of which overlap each other and other slices, again both in time and in the same track.

All of the other slices on that thread during those overhead slices look like children of those overhead slices, so the overhead slices are taken to be mostTopLevelSlices, so Slice groups them all together in a single slice hierarchy, so InputLatencyAsyncSlice lumps all of their flow events together, collecting everything any of them point to.
If those overhead slices weren't there, then Slice would be able to properly split their children up into tasks, and InputLatencyAsyncSlice be able to only follow the correct flow events.

Dan: can you look at why those overhead slices are broken?

**Comment by natduca** [comment] 2015-09-16 19:55
@dj2 i think we have to fix this p0...

**Comment by dj2** [comment] 2015-09-16 19:58
On the chromium side the person to talk to is wangxianzhu@ as he did the overhead implementation. Those numbers are definitely screwy, so it seems like something has gone wrong. We should probably file a chrome bug to track the fix.

For the tracing side, can we just artificially look for trace_event_overhead slices in the importer and force them into their own slice?

**Comment by natduca** [comment] 2015-09-22 18:45
We believe we can close this given that we are making progress on #1469

**Closed by natduca** 2015-09-22 18:45 UTC
Labels: Bug, Perf Insights, RAIL
