### ISSUE TITLE
Pinpoint - Surface trace links in UI

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#3919] opened 2017-09-26 16:11 UTC
Coming out of implementing the "request debug trace" functionality from dashboard. The chartjson contains the links, we just need to surface in a nice way.

@dave-2 @anniesullie

**Comment by dave-2** [comment] 2017-09-26 22:24
Duplicate of #3887

**Closed by dave-2** 2017-09-26 22:24 UTC
Labels: Bisect
