### ISSUE TITLE
TraceViewer dies due to JS OOM with a trace with 20+ renderers

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#1639] opened 2015-10-18 22:51 UTC
I was trying to grab a memory-infra trace on a Mac canary (I'm pretty sure the OS is irrelevant here). Just noticed that if I have ~20 tabs open it doesn't manage to process a trace longer than ~5-6 seconds.
If I record for longer the chrome://tracing tab dies while processing the trace (after the "Joining object refs"). I can see the chrome://tracing renderer tab peaking at more than 2GB and then dying.

Now, we seem to have two different problems here:
1) the heavy dumps (which in the default config are one every 2 sec.) are too heavy. Some dumpers are overly verbose. I'm going to track this issue separately on the chrome side. I got a 90 MB (uncompressed) trace after 6-7 seconds, which is not acceptable.  
2) Processing the dumps takes O(>> N) memory. I wonder if there is any low hanging fruit and easy fixable we are doing on the trace-viewer side while processing them.

**Comment by natduca** [comment] 2015-10-19 00:12
Mmm yeah I think we have a bit of a code-somecolor developing here around trace sizes and scaling in a few areas, as I'm seeing this for sampling data too... not sure what to do yet tho :)

@dj2  @nedn @vinterstum @fmeawad fyi

**Comment by nedn** [comment] 2015-10-19 10:48
@primiano can we generate the same trace file using telemetry, and use your awesome memory infra tool to analyze the memory usage of chrome://tracing importing that trace file.. 
<insert your recursive joke/>

**Comment by primiano** [comment] 2015-10-19 13:29
@nedn we can but I'm 90% sure about what the result will be: it will be all in v8 heap's new+old space
The best way is to use the devtools profiler on chrome://tracing (or on the dev server) to see if we are doing something terribly dumb there

**Comment by petrcermak** [comment] 2015-10-22 16:22
I've just started looking into the performance of importing memory dumps and I got the following results (12 memory dumps, 47 processes, ~70k total memory allocator dumps per heavy dump, ~18k total memory allocator dumps per light dump in total, no VM regions):

![screenshot from 2015-10-22 17 08 142](https://cloud.githubusercontent.com/assets/2546601/10671187/309db554-78e1-11e5-9087-94dc97ed3439.png)

I plan to investigate this further tomorrow, but here's a wild idea: How about we use _Workers_ to perform the imports in parallel?

**Comment by primiano** [comment] 2015-10-22 17:25
Well workers themselves won't solve the OOM issue though

**Comment by natduca** [comment] 2015-10-23 02:59
Workers are known busted in myriad other ways. I'd encourage us to avoid them if at all possible.

**Comment by petrcermak** [comment] 2015-10-23 09:41
**Memory:** I somehow missed that the issue was about memory. Unless there's a bug somewhere, I don't see how we could be using more than _O(N)_ memory.

The only thing (which I can think of right now) that we could in theory drop is the index in <tt>ContainerMemoryDump</tt> which maps full memory allocator dump names (e.g. 'v8/heaps/heap_42') to <tt>MemoryAllocatorDump</tt> objects. All indices in a single heavy/light memory dump have ~70k/~18k keys. This would, however, probably slightly decrease the performance of the UI.

**Workers:** Not worth it (especially because of d8).

**Comment by petrcermak** [comment] 2016-01-11 10:32
As bratell@opera.com suggested to me, the issue might be caused by too many **<tt>AttributeInfo</tt>** objects, which contain **long strings** (e.g. *"shares '(sliced string)' in global space (importance 0) with: - 'gpu/gl/textures/client_15/texture_1_face_0/..."*).

I will investigate this and modify the relevant code if this proves to be an issue: #1883.

**Comment by petrcermak** [comment] 2016-01-18 16:49
I analyzed the 8-second trace from YouTube TV provided by bratell@opera.com and found that there are indeed lots of long <tt>AttributeInfo</tt> strings _(**averages** per <tt>ProcessMemoryDump</tt> object, [link to full data](https://docs.google.com/a/chromium.org/spreadsheets/d/1dH4_2k4y05Ce19Kg36WUfUM7q6P38Q26kRbKcV0_UzY/edit?usp=sharing))_:

Dump type | <tt>MemoryAllocatorDump</tt> objects | <tt>Attribute</tt> objects | <tt>AttributeInfo</tt> chars
--------- | ------- | ------- | ---------
light     | 1,052.9 | 2,677.5 | 143,033.6
heavy     | 2,118.9 | 6,725.7 | 169,178.3
all       | 1,209.8 | 3,273.4 | 146,882.3

I then took a heap snapshot right after importing the trace (and finalizing it) and found that of the total 586 MiB, __<tt>AttributeInfo</tt> objects retain 130 MiB (22% of the total)__:

![screenshot from 2016-01-18 16 39 56](https://cloud.githubusercontent.com/assets/2546601/12396983/3e70683c-be02-11e5-8727-750c3b7afe71.png)

This is definitely a good enough reason to finally refactor the <tt>AttributeInfo</tt> messages (#1883).

**Comment by petrcermak** [comment] 2016-01-26 17:20
I have completely rewritten attribute info handling as promised (https://codereview.chromium.org/1629423004) and the results are even better than expected (on the 8-second trace from YouTube TV provided by bratell@opera.com): __the V8 heap shrank from 399 MiB to 289 MiB (27.5% memory reduction) after trace import__ :tada:. Screenshots of the results are attached below...

*Before*
![before_infos_overhaul](https://cloud.githubusercontent.com/assets/2546601/12587618/12c4f206-c44d-11e5-8f2b-87e85f124ccd.png)

*After*
![after_infos_overhaul](https://cloud.githubusercontent.com/assets/2546601/12587630/1848c450-c44d-11e5-87eb-820aafada311.png)

*Comparison*
![comparison_infos_overhaul](https://cloud.githubusercontent.com/assets/2546601/12587640/235c357a-c44d-11e5-92f8-f18d6aaf05d8.png)

**Comment by natduca** [comment] 2016-01-26 17:27
\o/

**Comment by petrcermak** [comment] 2016-02-05 16:00
As explained in my previous comment, the [patch](https://codereview.chromium.org/1629423004) that I've just landed __should reduce the memory usage of Memory-Infra by 20-30%__. Therefore, I'm now marking this bug as __fixed__ :white_check_mark:

If you still encounter memory-related issues, please file a new bug and _attach the corresponding trace_ (or send it to me). It's impossible to analyze memory usage without data!

**Closed by petrcermak** 2016-02-05 16:00 UTC
Labels: Bug, Code Health, Memory-Infra
