### ISSUE TITLE
Incorrect Associated Events for Load

### ISSUE THREAD

**Issue by dj2** [catapult-project/catapult#1429] opened 2015-09-02 14:58 UTC
Looking at [1] I'm seeing a strange set of associated events under some Load tasks. This trace was record on Android 40.0.2214.89 (the stock Chrome for this phone). The steps to record were:

1- Load cnn.com
2- When the page looks visually complete tap once
3- When the load indicator is done scroll slightly.

The load task highlighted in [2] seems a bit odd. The IR itself says it has a wall time of ~3.2seconds, but scrolling down through the trace I don't see any associated events for ~1.5seconds of the beginning.  Is it that the load started and just nothing happened or are we missing some associated events?

[1] https://drive.google.com/open?id=0BwBaQQ4lL3m2M0h4cWJXQWhrbm8
[2] https://drive.google.com/file/d/0BwBaQQ4lL3m2c0FxWUhmX3M1Tm8/view?usp=sharing

**Comment by dj2** [comment] 2015-09-02 14:59
@benshayden @philippebeaudoin

**Comment by dj2** [comment] 2015-09-02 15:42
I re-recorded with 44.0.2403.133 and the trace [1] (shared to @chromium.org) has similar load events. Specifically, the event that starts at 13,303.049ms (third load down in the second tree of loads) appears to have the first half of the load with no events.

[1] https://drive.google.com/open?id=0BwBaQQ4lL3m2dTQ5TTBXeWRDblE

**Comment by benshayden** [comment] 2015-09-02 16:36
Duplicate of #1221

**Closed** 2015-09-02 17:16 UTC
Labels: Bug, Perf Insights, RAIL
