### ISSUE TITLE
Perf Dashboard: 

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#2542] opened 2016-07-26 10:08 UTC
Chrome version: 53.0.2785.8 (Linux)
URL: https://chromeperf.appspot.com/report?sid=aa77fe5f7d0b7406b91e232fb319985c403a63cacb660836d381e5811ac9612c&start_rev=406680&end_rev=407706

Please describe the problem:
Sometimes when I create a new bug on a regression it says "started bisect", sometimes is not.
Is it WAI? I mean: is it the case that some benchmarks auto-trigger bisects on "new bug" and some other wait for my manual action? Or there is some bug under the hoods?

**Comment by anniesullie** [comment] 2016-07-26 11:48
There is one case where a bisect should not be auto-triggered: when the test is not bisectable, which should be just `sizes` on the main perf sheriff rotation. That certainly doesn't look like what happened here. crbug.com/631412 now has two bisects on it--did you file both manually?

**Comment by primiano** [comment] 2016-07-26 12:42
> did you file both manually?
Nope, I did only the 2nd manually, before I realized it was kicked off automatically.
I will try to be more careful in the next shift, but my feeling is that randomly sometimes I get the longer message (with bug id and bisect), and sometimes a shorted message (I don't even recall what's the shorted message anymore :/).

**Comment by primiano** [comment] 2016-07-26 13:09
Ah got it again on crbug.com/631461. After I clicked "new bug" I got a popup saying just "Bug created/updated" , but it definitely started a bisect.

**Comment by eakuefner** [comment] 2016-11-29 17:49
This is a dupe of #2971

**Closed by eakuefner** 2016-11-29 17:49 UTC
Labels: Perf Dashboard
