### ISSUE TITLE
Revision range selector doesn't correctly show possible ranges, doesn't update range

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#2074] opened 2016-02-26 21:32 UTC
https://chromeperf.appspot.com/group_report?bug_id=575911

First graph looks like this:
https://screenshot.googleplex.com/CjgbOWLRdMF

The data on the visible graph stretches from 2016-01-01 to 2016-02-19. However, the entire range of the selector shows 2016-02-19. If I try to expand it out, the graph refreshes and the selector snaps back to its old spot.

**Comment by qyearsley** [comment] 2016-03-08 17:38
This happens when the range of data available for the first item in the legend ("Filter") doesn't overlap with another item in the legend. There revision range selector is based on the first series listed, which in this case has no data in the revision range that the graph is showing.

This would be fixed if #1315 were fixed. OK to mark this as a dupe of that bug?

**Comment by anniesullie** [comment] 2016-07-12 20:57
Marking dupe.

**Closed by anniesullie** 2016-07-12 20:57 UTC
Labels: Bug, Perf Dashboard
