### ISSUE TITLE
Perf Dashboard: 

### ISSUE THREAD

**Issue by hlundin** [catapult-project/catapult#3195] opened 2017-02-08 13:17 UTC
Chrome version: 57.0.2987.19 (Linux)
URL: https://chromeperf.appspot.com/alerts?sheriff=WebRTC%20Perf%20Sheriff&sortby=test&sortdirection=down&improvements=true

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
(none)

Please describe the problem:
The counter reports 806 alerts, but the list is empty.

![image](https://cloud.githubusercontent.com/assets/8982948/22738808/3f8a4b24-ee09-11e6-9ba2-384c64b506cb.png)

**Comment by anniesullie** [comment] 2017-02-08 16:04
I can't repro, I'm seeing 0 alerts (also logged in):

![screen shot 2017-02-08 at 11 00 18 am](https://cloud.githubusercontent.com/assets/4331931/22745358/3f2301be-edee-11e6-9f00-3db8ce5bd6b8.png)

Is it possible you triaged the alerts on another page or something?

**Comment by simonhatch** [comment] 2017-02-08 16:06
Weird, I see the 806 alerts.

**Comment by anniesullie** [comment] 2017-02-08 16:09
That is definitely weird! @simonhatch since you can repro, can you take a look? Steps I would take are:

1. Looking at XHR to server to see what data it is filling in
2. Adding logging (or server-side debugging, if you can get that to work)

**Comment by hlundin** [comment] 2017-02-08 16:31
@anniesullie you have to hit "Show Improvements" too.

**Comment by anniesullie** [comment] 2017-02-08 16:40
Oh I missed that, sorry! Could be related to https://codereview.chromium.org/2669893003/

Not sure if @jessimb is in today/tomorrow?

**Comment by simonhatch** [comment] 2017-02-08 16:41
Dug into this, yeah it's just the showImprovements thing. I think @jessimb fixed it but we haven't deployed a new dashboard.

**Comment by simonhatch** [comment] 2017-02-08 16:44
Confirmed: https://clean-simonhatch-f20052d2-dot-chromeperf.appspot.com/alerts?sheriff=WebRTC%20Perf%20Sheriff&sortby=test&sortdirection=down&improvements=true

**Comment by simonhatch** [comment] 2017-02-08 16:45
New dashboard is live, closing this.

**Closed by simonhatch** 2017-02-08 16:45 UTC
Labels: Perf Dashboard

**Comment by hlundin** [comment] 2017-02-10 07:42
Verified. Thanks!
