### ISSUE TITLE
Sorting the alerts-table removed all rows with alert groups with more than one alert.

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#2453] opened 2016-07-06 17:39 UTC
To reproduce:

  1. Go to https://chromeperf.appspot.com/alerts?triaged=true
  2. Click on a header in the alerts-table (e.g. Master, Test Suite...)
  3. Observe that the table now contains no rows with numbers on the left, and the number of rows in the table is decreased.

Possibly related to #2452, which is possibly related to the dejinjification earlier this year (https://codereview.chromium.org/1709073003). Not sure if somebody has noticed this before or if this is a new bug.

@anniesullie @eakuefner

**Comment by anniesullie** [comment] 2016-07-11 15:26
This is a dupe of #2272.

**Closed by anniesullie** 2016-07-11 15:26 UTC
Labels: Bug, Perf Dashboard
