### ISSUE TITLE
need service to query by tags/metadata

### ISSUE THREAD

**Issue by dstockwell** [catapult-project/catapult#1502] opened 2015-09-22 23:24 UTC
I have been running several experiments against the top 1k websites, uploading thousands of navigation traces to my PI server.

My workflow is to sync all of the traces locally using `gsutil -m rsync -d -r gs://my-bucket .` But since the tags are not part of the trace I need a separate process to filter before mapping (and incidentally since `map_traces_locally` only understands directories I end up creating a ton of symlinks...). I've tried using the AppEngine's `remote_api_shell.py` but found it too slow. So in the meantime I have a hacked-up query service running on my PI server: https://gist.github.com/dstockwell/f9a8d03566155daf3fef

In my ideal local workflow, `map_traces_locally` would handle this. It would communicate with some sort of query service and transfer and cache trace files locally. But for now I have a reasonable workaround.

**Comment by fmeawad** [comment] 2015-09-22 23:26
We have been using the remote_api_shell for perf insights, and it has been OK so far. Maybe we can add more indexes or figure out better ways of optimizing the datastore.

**Comment by natduca** [comment] 2015-09-22 23:35
I think this is dupe of #1234... the bit about querying based on metdata is about using the --query parameter, to which you pass  a string that determines which traces you want. That is the corpus query and that can use any metdata for the corpus, which in the case of perf insights databases, would include the timestamp of the trace.

**Comment by natduca** [comment] 2015-09-22 23:35
@dstockwell if you're okay with caling this #1234, can you close this?

**Closed** 2015-09-22 23:39 UTC
Labels: Perf Insights
