### ISSUE TITLE
[📍] Pinpoint - Speedometer2 results aren't loading

### ISSUE THREAD

**Issue by gburgessiv** [catapult-project/catapult#4416] opened 2018-04-25 23:24 UTC
Hello,

Unsure if this is the right place to put this, but I'm having trouble loading the 'detailed' results for speedometer2 runs on Pinpoint.

Repro instructions:
- Go to https://pinpoint-dot-chromeperf.appspot.com/job/159d3fc5c40000
- Click "analyze benchmark results"
- See the page get stuck at "Loading Histogram 0 of 920"

This also happened on https://pinpoint-dot-chromeperf.appspot.com/job/16f71105c40000 .

I'm running Chrome 64 on MacOS 10.13.3. IIRC, it didn't work on my Chromebook earlier today, either.

Thank you!
George

**Comment by simonhatch** [comment] 2018-04-25 23:39
@dave-2

**Comment by simonhatch** [comment] 2018-04-25 23:40
@benshayden 

See some errors in dev console, are we embedding this wrong somehow?

```
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 786
    at JSON.parse (<anonymous>)
    at HistogramImporter.loadSomeHistograms_ (159d3fc5c40000.html?qk=AD5uMEubKBw2QCIwbxUKfRbb2C_KBhn9PkI2MuMdLGwihOcZqhmrXkji34Y2zJtAeVHGoC2gqR9M5H-0Lb2Z-RRZfN7BAJ8eWHfKInxllvSgbqNCaoqlViZ8JeyoLIJ-EaXb3gIB7qYK7wsWPXnRemlp6izja1xR3qejenjypuCklIURiX-tUNkhNYwwxiOBubjNJAJUd9zfgjZRUzt2C5f8Bkl_aKqbQSvqK0fzdW3MR-Ygr_zpElbvegJQfiGiKAbjMU5822InLyMh7fIfLjNv_9XlB6DKeIwMceR62cn6r7ZM4GhISebLjhMAACT32YTActn-zwNmg-NUp6qsyUWwMnWD-LfTkPgVxh1qDF9NK0MH2db6cT_FPuhDyA_8saYDxGxyCNLsnBtzq7E454W_VwfZCWIc0Gl2Ru17Br7Rj_7rQjRruUSFJpUC2O0JtsU2swUD8-_KOJ37QDOrFKGqWQ3VStInKaO_d5EXbgKJNWfAvbwIIdHmjRviB1jbQ9cuBl8lglmZKRZsBXXUIrZyDpc0xptWkEWGRHnNlbP_9pAl8O5pbi9BI9QPWV7Nv_Hr08VF8yojZ5vpP6DLO5eV6zJXfL4I1_Acj7u9CEQV1qJXHm6SAmQcL1tor2IPefjmmlpu1seoSIhc3id0sbFXNEdnJLZf4xFjYCdX6u9tL2rVddGNlDcFLeAIWcAnrigKivi1UzaXG1B3waZyifFiKwwz_rFFfP-LyAQ3GdrvplSZiAWu1yM:18183)
    at HistogramImporter.importHistograms (159d3fc5c40000.html?qk=AD5uMEubKBw2QCIwbxUKfRbb2C_KBhn9PkI2MuMdLGwihOcZqhmrXkji34Y2zJtAeVHGoC2gqR9M5H-0Lb2Z-RRZfN7BAJ8eWHfKInxllvSgbqNCaoqlViZ8JeyoLIJ-EaXb3gIB7qYK7wsWPXnRemlp6izja1xR3qejenjypuCklIURiX-tUNkhNYwwxiOBubjNJAJUd9zfgjZRUzt2C5f8Bkl_aKqbQSvqK0fzdW3MR-Ygr_zpElbvegJQfiGiKAbjMU5822InLyMh7fIfLjNv_9XlB6DKeIwMceR62cn6r7ZM4GhISebLjhMAACT32YTActn-zwNmg-NUp6qsyUWwMnWD-LfTkPgVxh1qDF9NK0MH2db6cT_FPuhDyA_8saYDxGxyCNLsnBtzq7E454W_VwfZCWIc0Gl2Ru17Br7Rj_7rQjRruUSFJpUC2O0JtsU2swUD8-_KOJ37QDOrFKGqWQ3VStInKaO_d5EXbgKJNWfAvbwIIdHmjRviB1jbQ9cuBl8lglmZKRZsBXXUIrZyDpc0xptWkEWGRHnNlbP_9pAl8O5pbi9BI9QPWV7Nv_Hr08VF8yojZ5vpP6DLO5eV6zJXfL4I1_Acj7u9CEQV1qJXHm6SAmQcL1tor2IPefjmmlpu1seoSIhc3id0sbFXNEdnJLZf4xFjYCdX6u9tL2rVddGNlDcFLeAIWcAnrigKivi1UzaXG1B3waZyifFiKwwz_rFFfP-LyAQ3GdrvplSZiAWu1yM:18155)
```

**Comment by eakuefner** [comment] 2018-04-25 23:42
Almost certainly, this is a dupe of #4415.

**Comment by dave-2** [comment] 2018-04-25 23:44
Closing as a duplicate of #4415

**Closed by dave-2** 2018-04-25 23:44 UTC
Labels: Bisect
