### ISSUE TITLE
Starting a new pinpoint task broken

### ISSUE THREAD

**Issue by sadrulhc** [catapult-project/catapult#4464] opened 2018-05-18 15:27 UTC
When trying to add a new task from https://pinpoint-dot-chromeperf.appspot.com/, after filling out the gerrit URL, selecting a bot, and entering the benchmark name, clicking 'Start' fails with the following error: '__init__() got an unexpected keyword argument 'scope''

**Comment by simonhatch** [comment] 2018-05-18 15:32
Thanks, will take a look after this dashbaord issue.

**Comment by simonhatch** [comment] 2018-05-18 15:58
Looks like same root cause as the dashboard issue, #4465 , CL out for review.

**Comment by simonhatch** [comment] 2018-05-18 16:35
Deployed version of dashboard works and pinpoint jobs start, closing.

**Closed by simonhatch** 2018-05-18 16:35 UTC
Labels: Bisect

**Comment by sadrulhc** [comment] 2018-05-18 16:57
Thank you for the quick fix!
