### ISSUE TITLE
Error fetching browser log: "TypeError: coercing to Unicode: need string or buffer, NoneType found"

### ISSUE THREAD

**Issue by kenrussell** [catapult-project/catapult#2441] opened 2016-06-28 23:50 UTC
In many failing test runs recently the following stack trace has shown up:

`Minidump found: e:\b\swarm_slave\work\isolated\isolated_tmpqumjwn\tmpx6zctp\reports\bce0b7f5-81f0-4dfd-8405-ead6bdc30a5a.dmp
  *************** BROWSER STANDARD OUTPUT ***************
  
  *********** END OF BROWSER STANDARD OUTPUT ************
  ********************* BROWSER LOG *********************
  Failed to get browser log:
  Traceback (most recent call last):
    File "e:\b\swarm_slave\work\isolated\isolated_rungebusn\third_party\catapult\telemetry\telemetry\internal\browser\browser.py", line 335, in DumpStateUponFailure
      logging.info(self.GetLogFileContents())
    File "e:\b\swarm_slave\work\isolated\isolated_rungebusn\third_party\catapult\telemetry\telemetry\internal\browser\browser.py", line 276, in GetLogFileContents
      return self._browser_backend.GetLogFileContents()
    File "e:\b\swarm_slave\work\isolated\isolated_rungebusn\third_party\catapult\telemetry\telemetry\internal\backends\browser_backend.py", line 43, in GetLogFileContents
      with file(self.log_file_path) as f:
  TypeError: coercing to Unicode: need string or buffer, NoneType found
  ***************** END OF BROWSER LOG ******************
`

Example failing tryjob:
https://build.chromium.org/p/tryserver.chromium.win/builders/win_chromium_rel_ng/builds/246705

Full stdout attached.

[stdout.txt](https://github.com/catapult-project/catapult/files/338270/stdout.txt)

Assigning to @petrcermak on recommendation from @nedn .

**Comment by nedn** [comment] 2016-06-29 13:25
@perezju is working on this.

**Comment by perezju** [comment] 2016-06-29 14:08
Duplicate of #2445

**Closed by perezju** 2016-06-29 14:08 UTC
Labels: Telemetry
