### ISSUE TITLE
Reland Add support for clock sync events to tracing controller.

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2062] opened 2016-02-24 16:54 UTC
Example stdio: https://build.chromium.org/p/tryserver.chromium.win/builders/win_chromium_rel_ng/builds/178762/steps/telemetry_perf_unittests%20%28with%20patch%29%20on%20Windows-7-SP1/logs/stdio

```
[22/170] benchmarks.benchmark_smoke_unittest.BenchmarkSmokeTest.blob_storage.blob_storage failed unexpectedly 0.4640s:
  [ RUN      ] blob-mass-create-2Bx200
  Traceback (most recent call last):
    File "e:\b\swarm_slave\work\isolated\runoze_d9\third_party\catapult\telemetry\telemetry\internal\story_runner.py", line 76, in _RunStoryAndProcessErrorIfNeeded
      test.WillRunStory(state.platform)
    File "e:\b\swarm_slave\work\isolated\runoze_d9\third_party\catapult\telemetry\telemetry\web_perf\timeline_based_measurement.py", line 263, in WillRunStory
      platform.tracing_controller.StartTracing(self._tbm_options.config)
    File "e:\b\swarm_slave\work\isolated\runoze_d9\third_party\catapult\telemetry\telemetry\core\tracing_controller.py", line 35, in StartTracing
      self._tracing_controller_backend.StartTracing(tracing_config, timeout)
    File "e:\b\swarm_slave\work\isolated\runoze_d9\third_party\catapult\telemetry\telemetry\internal\platform\tracing_controller_backend.py", line 70, in StartTracing
      self.StartAgentTracing(config, timeout)
    File "e:\b\swarm_slave\work\isolated\runoze_d9\third_party\catapult\telemetry\telemetry\internal\platform\tracing_controller_backend.py", line 115, in StartAgentTracing
      trace_event.trace_enable(self._trace_log)
    File "e:\b\swarm_slave\work\isolated\runoze_d9\third_party\catapult\tools\py_trace_event\py_trace_event\trace_event.py", line 69, in trace_enable
      return trace_event_impl.trace_enable(logfile)
    File "e:\b\swarm_slave\work\isolated\runoze_d9\third_party\catapult\tools\py_trace_event\py_trace_event\trace_event_impl\log.py", line 50, in trace_enable
      _trace_enable(log_file)
    File "e:\b\swarm_slave\work\isolated\runoze_d9\third_party\catapult\tools\py_trace_event\py_trace_event\trace_event_impl\log.py", line 39, in locked_fn
      ret = fn(*args,**kwargs)
    File "e:\b\swarm_slave\work\isolated\runoze_d9\third_party\catapult\tools\py_trace_event\py_trace_event\trace_event_impl\log.py", line 58, in _trace_enable
      raise TraceException("Tracing control not allowed in child processes.")
  TraceException: Tracing control not allowed in child processes.
```

Here is the list of CLs in the roll:
https://chromium.googlesource.com/external/github.com/catapult-project/catapult.git/+log/5d995e9b3026..20e4ed07fc41

@eakuefner This looks related to https://codereview.chromium.org/1724123002. Can you take a look?

**Comment by eakuefner** [comment] 2016-02-24 17:03
@nedn @randalnephew This is more fallout from https://chromium.googlesource.com/external/github.com/catapult-project/catapult.git/+/6a59f92d621a9c6783625311797b4a7ee3dcb671 and there are too many tests to just @decorators.Isolated on all of them. That will probably lead to unacceptable cycle time blowup for telemetry_perf_unittests.

What should we do?

**Comment by eakuefner** [comment] 2016-02-24 17:06
In addition there's another kind of assertion failure on some tests:

  Traceback (most recent call last):
    _RunStoryAndProcessErrorIfNeeded at third_party\catapult\telemetry\telemetry\internal\story_runner.py:110
      test.DidRunPage(state.platform)
    DidRunPage at tools\perf\measurements\oilpan_gc_times.py:157
      platform.tracing_controller.StopTracing()
    StopTracing at third_party\catapult\telemetry\telemetry\core\tracing_controller.py:39
      return self._tracing_controller_backend.StopTracing()
    StopTracing at third_party\catapult\telemetry\telemetry\internal\platform\tracing_controller_backend.py:107
      '\n'.join(raised_exception_messages))
  TracingControllerStoppedError: Exceptions raised when trying to stop tracing:
  Traceback (most recent call last):
    File "e:\b\swarm_slave\work\isolated\runoze_d9\third_party\catapult\telemetry\telemetry\internal\platform\tracing_controller_backend.py", line 96, in StopTracing
      agent.StopAgentTracing(trace_data_builder)
    File "e:\b\swarm_slave\work\isolated\runoze_d9\third_party\catapult\telemetry\telemetry\internal\platform\tracing_controller_backend.py", line 120, in StopAgentTracing
      assert trace_event.trace_is_enabled(), 'Tracing not running.'
  AssertionError: Tracing not running.

**Comment by eakuefner** [comment] 2016-02-24 17:12
Revert: https://codereview.chromium.org/1736583002/

**Comment by randalnephew** [comment] 2016-02-24 17:17
That second error is a cascading failure caused by the first problem. The first one puts trace_event into a bad state and since it stores things at the module level it affects all subsequent test runs. 

This should fix the issue, but has been shot down: https://docs.google.com/document/d/1B8zDQuLoOTvxRcYq176ocLV7j1X0NcWmCpDNgkGMJTk/edit

Other than using @decorators.Isolate I do not know if there is a way the current implementation can be used since the tests can all affect one another.

**Comment by nedn** [comment] 2016-02-24 17:22
Randy: is that the problem of telemetry tracing enabled by default? We can make it disabled by default.

**Comment by eakuefner** [comment] 2016-02-24 17:22
Randy, can you adjust the perms on that doc?

**Comment by natduca** [comment] 2016-02-24 17:23
Yeah I don't think its fair to point at this being a bug of py_trace_event or an issue with how py-trace-event has globals. Your real critique is that the way we're integrating py_trace_event into typ is problematic.

**Comment by randalnephew** [comment] 2016-02-24 17:34
Permissions should be fixed.

I dont think the integration at present would be a global tracer. The current use of py_trace_event is to just create the log in the tracing_controller_backend so that we can have a tracing_controller log that contains the clock syncs. Each instances of tracing_controller_backend would have their own Tracer() object.

**Comment by nedn** [comment] 2016-02-24 17:56
To summarize the problem, py_trace_event does not allows python subprocesses to control tracing. It achieves this by shimming out multiprocessing module to mark whether the current python process is a subprocess.

This is a trouble for telemetry unittest that run under typ, because typ create a bunch of subprocesses to parallelize telemetry test.
I can think of 2 fixes here:

1) Admitting that telemetry's python tracing is not always available (just like battor tracing cannot always be available). Hence telemetry's tracing_controller is adjusted to tolerate the possibility that it cannot produce the controller's trace. Majority of tests that invoke tracing in telemetry_perf_unittest are mostly smoke test, hence the lack of tracing_controller's trace shouldn't be problems there. 

2) Importing py_trace_event modules dynamically inside tracing_controller_backend.StartTracing & StopTracing method. This will make sure that the limitation that "subprocesses cannot start tracing" only apply beyond the point of tracing_controller_backend.StartTracing(), hence each process that run telemetry benchmark smoke tests can still have their own tracer. If any of those processes fork other subprocesses, those "grandchildren" subprocesses will not be able to control tracing.

**Comment by randalnephew** [comment] 2016-02-24 18:03
I could add IsTracingControlable() to trace_event that returns _control_allowed and have tracing_controller_backend use this to determine if it will attempt clocksyncs / controller tracing.

**Comment by nedn** [comment] 2016-02-24 19:40
That plan SGTM. @natduca wdyt?

**Comment by natduca** [comment] 2016-02-24 19:43
I like it!

**Comment by randalnephew** [comment] 2016-02-24 19:55
It also looks like when this problem happens, it causes a fd to be left open in py_trace_event. Windows will not allow you to delete a file with an open fd.

WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'e:\\b\\swarm_slave\\work\\isolated\\tmpu3wt8p\\tmpwflxfl'

I am also going to add some logic to detect that it fails to remove the log file after it is used. If it fails, it will register an atexit function to attempt to delete it again, and will throw an exception then if it fails.

CL is here, I'll be sending it out for review shortly:
https://codereview.chromium.org/1736613002/

**Comment by eakuefner** [comment] 2016-02-26 18:07
Can this bug be closed?

**Comment by randalnephew** [comment] 2016-02-29 21:48
Yes, I am bad at closing bugs.

**Closed by randalnephew** 2016-02-29 21:48 UTC
Labels: Gardening, Infrastructure, Telemetry
