### ISSUE TITLE
Feature Request: Add comments to alerts

### ISSUE THREAD

**Issue by tednakamura** [catapult-project/catapult#1353] opened 2015-08-24 22:48 UTC
(This was originally filed in http://crbug.com/338045, but I'm refiling this request here per the latest comment/bulk edit.)

tl;dr - in the perf dashboard, it would be useful to be able to add a comment that explains why you flagged an alert as invalid or ignored.

**Comment by anniesullie** [comment] 2016-07-14 14:17
Closing as a dupe of #2270

**Closed by anniesullie** 2016-07-14 14:17 UTC
Labels: Enhancement, P3, Perf Dashboard
