### ISSUE TITLE
Perf Dashboard: No way to sign-out or switch accounts

### ISSUE THREAD

**Issue by rmcilroy** [catapult-project/catapult#3850] opened 2017-09-08 07:20 UTC
I couldn't find a way to switch from my Google account to my Chromium account on the chromium perf dashboard without either signing out from Google everywhere (there is no signout button on the perf dashboard that I can see) or opening the dashboard in incognito mode.

Chrome version: 60.0.3112.101 (Mac)
URL: https://chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down

**Comment by simonhatch** [comment] 2017-09-11 14:04
Dupe of #3536

**Closed by simonhatch** 2017-09-11 14:04 UTC
Labels: Perf Dashboard
