### ISSUE TITLE
Get deep reports to include v8 samples

### ISSUE THREAD

**Issue by natduca** [catapult-project/catapult#1304] opened 2015-08-20 22:46 UTC
We probably want deep reports to include v8 samples now that we support them.

@fmeawad @chiniforooshan @dj2

**Comment by fmeawad** [comment] 2015-08-25 20:45
+ @dj2

**Comment by fmeawad** [comment] 2015-08-25 20:47
This would require enabling v8.cpu_profile (disabled-by-default), I will do an experiment to see how that affects the size and if it is still OK for the upload.

If it makes the trace file too bug, we can enable it on fast connections only.

**Comment by dj2** [comment] 2015-08-25 20:47
I think we want this on for all customers. If the file is too big we'll need to investigate how we can make the format more compact.

**Comment by chiniforooshan** [comment] 2015-08-25 20:58
What is considered too big? If I remember correctly, it increases the trace file size roughly by a factor of 10.

**Comment by fmeawad** [comment] 2015-08-25 22:00
I have a magic number of 2MB on fast connections and 500KB and 2G. (Compressed for a 30s trace).

**Comment by fmeawad** [comment] 2015-08-26 22:55
I have made an experiment to enable v8.cpu_profile category on deep reports and the trace size only doubled (which I can deal with) but the samples does not seem to be useful, as follow is a screen shot of the stack trace of "every" sample. Is there anything I am missing to make it work properly?

![screenshot from 2015-08-26 15 52 03](https://cloud.githubusercontent.com/assets/1760798/9508469/7df91cd4-4c0a-11e5-970a-ba12dd46e6b2.png)

**Comment by fmeawad** [comment] 2015-08-26 22:55
@vinterstum

**Comment by dj2** [comment] 2015-08-27 02:05
You need ToT trace viewer. If you run the dev server and look at the trace you should see all the sampling information.

**Comment by dj2** [comment] 2015-09-09 14:14
@fmeawad any update on if/when this will be enabled for deep reports?

**Comment by fmeawad** [comment] 2015-09-17 18:08
@dj2 On latest trace-viewer, it times out when loading the trace.
Trace is too big to attach and/or wrong format.
https://drive.google.com/file/d/0B7Nc8cbDG517UVp4d0NaRldtZVk/view?usp=sharing

**Comment by fmeawad** [comment] 2015-09-17 18:20
Link in previous comment updated

**Comment by natduca** [comment] 2015-09-17 18:34
@chiniforooshan fyi

**Comment by fmeawad** [comment] 2015-09-17 20:05
On a 30s trace, the trace size increased from ~3.8MB to ~4.8MB compressed. It is an acceptable increase on my side. Reducing it further would be nice, but if not, and given the importance of that data, I will enable it in the wild and see. But I would like to wait until the timeout issue mentioned above is solved.

**Comment by dj2** [comment] 2015-09-17 21:05
I can repro the loader hang, I'll see if I can figure out where it's getting wedged.

**Comment by dj2** [comment] 2015-09-17 21:05
One question, is it all of the traces you got, or did we just happen to get a bad one?

**Comment by fmeawad** [comment] 2015-09-18 17:13
All of them, I have not encountered one that worked. Although my chrome build is 2 weeks old. Refreshing to ToT and retrying.

**Comment by fmeawad** [comment] 2015-09-18 20:09
Reproduced on ToT

**Comment by chiniforooshan** [comment] 2015-09-18 20:20
For the attached trace file, it's choking on a JitCodeAdded event. I'll take a look...

**Comment by chiniforooshan** [comment] 2015-09-18 22:46
The issue is number precisions in JS. The trace file has large addresses like 0xffffffff9f90a1a0 which loose precision when parsed to a number in JS. This is why the while loop in CodeMap.deleteAllCoveredNodes_ may never terminate. I'll try to think of a solution on Monday.

**Comment by dj2** [comment] 2015-09-21 14:48
This was fixed by DevTools when they added their own code map. (https://codereview.chromium.org/1086083005) which we can try to integrate. I can also take a look and see what the v8 teams' code map is currently doing. I'm not sure if it was built to handle the 64bit binaries.

We can't just replace the v8 one with the devtools one as the v8.log data has other information in it that the v8 code map is storing. The quick solution maybe to have 2 for now and figure out how to reconcile them later.

**Comment by natduca** [comment] 2015-09-21 16:14
We have historically represented pointers as strings in other parts of tracing. E.g. thing: "0x100000" instead of thing: 0x100000. Does that apply here?

**Comment by dj2** [comment] 2015-09-21 16:39
The problem is, when we get a code map entry it comes with an address and a size. Any addresses we have in the map that are overlapped by that address and size have to be removed.

So, we need them as numbers so we can do the overlap calculations. We also need it as numbers because a lookup address will be a number somewhere in the address + size range and we need to be able to find it.

**Comment by dj2** [comment] 2015-09-21 19:29
Ok, at first pass at fixing this has landed. @fmeawad can you try it out with some more of your traces? The one linked above worked for me.

**Comment by fmeawad** [comment] 2015-09-21 19:32
I tried it on the patch, and it worked perfectly. I will wait for a Roll the enable it in deep reports.

**Comment by dj2** [comment] 2015-09-21 20:06
Fixed.

**Comment by fmeawad** [comment] 2015-09-21 20:09
Re-opening until it lands in deep reports as per the bug Title.

**Comment by fmeawad** [comment] 2015-09-24 00:23
Landed in https://codereview.chromium.org/1361793002/

**Closed by fmeawad** 2015-09-24 00:23 UTC
Labels: Data Pipeline
