### ISSUE TITLE
Perf Dashboard: Cannot triage new bug due to "500 Internal Server Error

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2526] opened 2016-07-21 14:52 UTC
Chrome version: 51.0.2704.79 (Linux)
URL: https://dev-sullivan-74e2605e-dot-chromeperf.appspot.com/alerts?sheriff=System%20Health%20Perf%20Sheriff&sortby=end_revision&sortdirection=down

Repro steps:
1. Go to https://dev-sullivan-74e2605e-dot-chromeperf.appspot.com/alerts?sheriff=System%20Health%20Perf%20Sheriff&sortby=end_revision&sortdirection=down
2. Select the first alert.
3. Click on "TRIAGE".
4. Click on "NEW BUG".
5. Click on "Submit".

Please describe the problem:
![screenshot from 2016-07-21 15 50 32](https://cloud.githubusercontent.com/assets/2546601/17027213/e9c9d51c-4f5a-11e6-9811-1b316ae225af.png)

**Comment by petrcermak** [comment] 2016-07-21 14:54
I've just noticed that the [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=630290) was created anyway (more than once), but no bisect was started.

**Comment by petrcermak** [comment] 2016-07-21 14:56
The error also happens when you try to triage from the [graph page](https://dev-sullivan-74e2605e-dot-chromeperf.appspot.com/report?sid=a1f473f06c4ae7489846766cf4c11058f6fc4d4b647b5da8ea53b26b38756fb0&rev=406222) (no bug was filed this time):

![screenshot from 2016-07-21 15 55 09](https://cloud.githubusercontent.com/assets/2546601/17027389/984bc17c-4f5b-11e6-9ad8-cce07dfca9a5.png)

**Comment by Apeliotes** [comment] 2016-07-26 21:44
I haven't been able to repro this on tot today. I went through the logs and saw some DeadlineExceededErrors, which would cause a 500 error if we didn't catch it or didn't respond quickly enough.

More recent demo: https://dev-aiolos-1c4bc232-dot-chromeperf.appspot.com

**Comment by Apeliotes** [comment] 2016-07-26 22:03
It sounds like people were hitting this occasionally prior to the migration. I think the actual fix for this is going to be getting a better datastore that handles a higher qps.

**Comment by anniesullie** [comment] 2016-07-27 12:55
Closing as a dupe of #2536.

**Closed by anniesullie** 2016-07-27 12:55 UTC
Labels: P1, Perf Dashboard, Polymer 1.0 Migration
