### ISSUE TITLE
New issues discovered on ToT are marked with Stable milestone number

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#2906] opened 2016-10-06 10:22 UTC
Repro:
1.) Alert from V8's perf bots on ToT
2.) Create an an issue out of the alert
3.) Issue gets the current Stable version assigned

Example: https://bugs.chromium.org/p/chromium/issues/detail?id=650236

**Comment by natorion** [comment] 2017-01-09 12:52
This is still happening and annoying (and potentially dangerous) :-(. If a proper fix is not possible please simply omit adding the milestone label at all. In that case the information is at least not incorrect.

**Comment by anniesullie** [comment] 2017-01-09 13:38
@jessimb can you look into this today? @benhenry can probably help you understand milestone numbers<->commit positions.

**Comment by jessimb** [comment] 2017-01-09 18:48
For the alert in question, the start_revision is 39684, much too low to be a Chromium commit revision number, likely a v8 revision number. 
The way labeling a milestone works currently, is to get the list of current milestones and their branch_base_positions and find the first milestone after the given revision. So when you pass in anything lower than the current stable branch (aka a v8 revision number) it will find the stable version every time.

There seem to be two courses of action here:
-If an alert contains a start_revision much lower than the branch_base_position of the oldest current version (as reported by OmahaProxy), do not label with a milestone number.
-Determine if the reported revision is from v8, if so determine which milestone it corresponds to, if appropriate.

**Comment by jessimb** [comment] 2017-01-09 19:16
After offline conversation with @eakuefner, we think that the older alerts (assuming they are Chromium commits) should be labeled with the oldest stable version, as they might still be release blockers. The current logic surrounding this works as intended.

The problem is that sometimes callers pass in revisions that are not Chromium revisions. This is true for v8 but also for other repositories (Clank, etc.). To fix it, we need to do something like verifying if the passed revision refers to a Chromium commit or not.

**Comment by jessimb** [comment] 2017-01-09 19:28
The best solution for this bug would be to determine which repository the alert corresponds to, and determine how that relates to milestone versions. That requires quite a bit of extra plumbing and is probably out of scope here.

As a workaround, we can filter on master and only label alerts that we know are Chromium (i.e. ChromiumPerf and ChromiumPerfFyi). Stay tuned for a CL on this.

**Comment by anniesullie** [comment] 2017-01-09 20:06
Do we have the Row entity at this point in the code? The point id should correspond to one of the supplemental columns, which have names like 'r_chromium_commit_pos' and 'r_webrtc' so it should be possible to check which one it is and whitelist the valid names.

**Comment by jessimb** [comment] 2017-01-09 20:13
I believe we only have the alert_keys. See relevant code https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/file_bug.py#L120

**Comment by jessimb** [comment] 2017-01-09 20:21
CL to skip labeling for non ChromiumPerf and ChromiumPerfFyi masters: https://codereview.chromium.org/2618413002

**Comment by natorion** [comment] 2017-01-10 09:47
Thanks folks!

**Comment by perezju** [comment] 2017-01-16 09:41
Will this stop tagging milestones on bugs for clank alerts? That would be a regression from our point of view.

**Comment by anniesullie** [comment] 2017-01-17 16:13
@jessimb Can you take another look? How did this previously work for clank, since it used timestamps for revs?

**Comment by perezju** [comment] 2017-01-17 16:26
Note sure how it was implemented, but this is an example of a [clank bug](https://bugs.chromium.org/p/chromium/issues/detail?id=655135) that somehow was auto-tagged with the correct milestone number.

**Comment by anniesullie** [comment] 2017-01-17 16:27
Thanks, Juan!

**Comment by jessimb** [comment] 2017-01-17 18:51
What I suspect is happening here is the opposite of V8's problem - the revision that is being passed in from the Anomaly is 1476193324, much too high to be a Chromium commit revision number. The algorithm decides which milestone branching point is closest to that revision, so in this case it will always choose the highest (Dev) version. If that happens to be correct each time, that is just a happy accident. 

If that is the desired behavior, should we add ClankInternal to the list of masters? I'm not sure the best course of action here.

**Comment by anniesullie** [comment] 2017-01-17 18:55
@perezju: Does that explanation sound correct to you?

If that's what's happening, maybe we should check for a specific named commit (`r_chromium_commit_pos` or whatever it is named in these `Row` entities). That should work for all waterfalls that support chromium commit positions.

**Comment by jessimb** [comment] 2017-01-17 19:04
At this point, we only have the `Anomaly` key; is there a way to trace that back to the `Row`? As far as I can tell, we can only glean information about where the `Anomaly` comes from via the `test` and `sheriff`.

**Comment by perezju** [comment] 2017-01-18 10:24
Ah! Yes, you are right Jessi, this used to work for clank "by accident". As Annie points out the correct solution would probably involve plumbing the revision values through so that `r_commit_pos` is available on the anomalies. This might be needed anyway for the sort of things requested in #3014.

**Comment by anniesullie** [comment] 2017-01-18 15:03
Yep! @perezju is right, `r_commit_pos` is set for all these revisions. I verified that using that should be safe for v8 data; they seem to send just `r_v8_git` So switching the code to:

1.  Get the alert (I think you could move [this code](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/models/stoppage_alert.py#L51) to the base class)
2. Check `r_commit_pos`

**Comment by jessimb** [comment] 2017-01-19 19:44
I see that we use `start_revision` when trying to figure out which milestone the alert may belong to [(relevant code)](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/file_bug.py#L228). But, to find the `Row` associated with the alert, we must look it up via `end_revision`. In the interest of code complexity, @anniesullie thinks (and I agree) that we should be using the `end_revision` of the alerts throughout the function. 

Any objections? @perezju

**Comment by perezju** [comment] 2017-01-23 17:33
Yeah, no objections from here.

I've sometimes found `start_revision` to be a bit strange anyway. As far as I can tell it's something like the `end_revision` of the previous point `+ 1`, which doesn't always make sense (e.g. when these "revisions" are in fact timestamps).

**Comment by benhenry** [comment] 2017-01-23 18:47
end_revision sounds correct to me as well since we have a single git
revision/hash per branch per project.

Ben

**Comment by eakuefner** [comment] 2017-01-31 00:03
`start_revision` vs. `end_revision` hurts my brain. I was talking to @jessimb offline about this and I wonder if that concept can be eliminated in favor of simply "here's the revision the alert is pegged at"?

Does anyone (or any code) actually use the fact that begin/end is a window for anything? Perhaps when grouping alerts it's good to show a range, but if each individual alert were simply tagged with "this is where the alert occurs", you just have to take the min and max across the group rather than doing interval merging, so that logic would anyway be simplified.

**Comment by anniesullie** [comment] 2017-01-31 00:06
You'd need to do a full search of the code to propose a refactor to remove all usages, but `start_revision` is a concept used in a lot of places, including alert overlap, tooltip UI, and alerts table UI.

**Comment by perezju** [comment] 2017-01-31 09:39
Yes, the start/end-revision range also gives the list of CLs between two points and therefore the bisect range. And I think that you really need to reason about these ranges to make alert grouping work.

I believe the main source of confusion is, however, that these start/end-revisions are actually point ids and *not* necessarily revisions.

**Comment by jessimb** [comment] 2017-02-01 23:41
Closing this issue as it should be fixed now.

**Closed by jessimb** 2017-02-01 23:41 UTC
Labels: Hotlist:v8, Perf Dashboard
