### ISSUE TITLE
Always monitor all sub-series results (in a reasonable and helpful way).

### ISSUE THREAD

**Issue by qyearsley** [catapult-project/catapult#1673] opened 2015-10-27 18:28 UTC
Background: In general for the Chromium Perf Sheriff rotation, the series on the dashboard that are monitored are summary series, which a generally averages of the results of several pages. Regressions sometimes only manifest on some pages (or are more pronounced on some pages).

Currently the dashboard monitors individual series (e.g. only the summary series) but the data in the dashboard is structured hierarchically, and per-page results are always below the summary series.

It's possible to just monitor all of the per-page results; I made a perf sheriff rotation like this, in order to see how it looks: [Sub-series perf sheriff rotation](https://chromeperf.appspot.com/alerts?sheriff=Chromium%2BPerf%2BSheriff%2B-%2BSub-series), however the alert volume is very high.

Goals:
 * Don't increasing triaging workload.
 * Alert when only one or two pages regress, even when there are many pages in a page set and the summary metric is relatively noisy.
 * Show the sheriff which pages had the biggest regression, so that bisect can be done on the most helpful page.

**Comment by qyearsley** [comment] 2015-10-27 18:30
Planning doc: https://docs.google.com/document/d/1vywTutgDkbdgtA5eBqrh8fzBCJNERsNFTLMPNQ-xaDo/edit#

**Comment by anniesullie** [comment] 2015-10-27 18:47
A few questions:

1.  Is the sub-series perf sheriff rotation complete? (I mean, does it include all tests currently monitored by the chromium sheriff?)
2.  Is there an easy way to tweak the alerting just for the sub-series sheriff? I think we need to make it less sensitive.
3.  Is there some easy way to clear all the alerts older than 24 hours?

If all these are done/doable, I think we should do perf sheriffing on the sub-series sheriff, with some predetermined bug ids:

  * Alerting too sensitive
  * Tests too noisy
  * Grouping not good enough
  * LGTM

Each rotation is one day, and at the end we see what we can do about the first 3 (tweak the sheriffing algorithm, contact test owners about noisy tests, tweak grouping algorithm). WDYT?

@dave-2 since he is interested in this topic.

**Comment by qyearsley** [comment] 2015-10-27 19:20
1. Almost. I added all tests that have per-page sub-series, for which the per-page sub-series were not already monitored. Specifically, the test path patterns that the main perf sheriff rotation includes for which there are no corresponding monitored tests in the sub-series perf sheriff rotation are:
 * `ChromiumPerf/*/blink_perf.*/*/*`
 * `ChromiumPerf/*/cc_perftests/*/*/*`
 * `ChromiumPerf/*/dom_perf/Total/score`
 * `ChromiumPerf/*/dromaeo.dom*/dom`
 * `ChromiumPerf/*/image_decoding.image_decoding_measurement/ImageDecoding_avg`
 * `ChromiumPerf/*/indexeddb_perf/Total Perf`
 * `ChromiumPerf/*/jetstream/Score`
 * `ChromiumPerf/*/kraken/Total`
 * `ChromiumPerf/*/mach_ports/mach_ports`
 * `ChromiumPerf/*/smoothness.gpu_rasterization.tough_filters_cases/frame_times/*`
 * `ChromiumPerf/*/smoothness.tough_filters_cases/frame_times/*`
 * `ChromiumPerf/*/spaceport/Score`
 * `ChromiumPerf/*/speedometer/Total`
 * `ChromiumPerf/*/sunspider/Total`

2. There's an anomaly threshold config called "sub-series" (which can be seen and edited on https://chromeperf.appspot.com/edit_anomaly_configs). Current thresholds are:
```
{
  "min_relative_change": 0.050000000000000003, 
  "min_steppiness": 0.5
}
```

To bulk-delete all alerts older than a certain time for a sheriff, one could run snippet like this on [the interactive console](chromeperf.appspot.com/_ah/dev_console/interactive):
```
import datetime
from google.appengine.ext import ndb
from dashboard.models.anomaly import Anomaly

sheriff = ndb.Key('Sheriff', 'Chromium Perf Sheriff - Sub-series')
time_cut_off = datetime.datetime.now() - datetime.timedelta(days=1)
q = Anomaly.query(
    Anomaly.sheriff == sheriff,
    Anomaly.timestamp < time_cut_off)
keys = q.fetch(keys_only=True, limit=5000)
print 'Going to delete %d Anomaly entities.' % len(keys)
ndb.delete_multi(keys)
```

It will likely be unclear sometimes what category some alerts belong to (test too "noisy" may also imply alerting too sensitive, and grouping is perhaps a separate issue), and these special bug IDs may quickly grow to contain hundreds of alerts, which may be hard to manage.

Earlier you suggested two special bug IDs (OK and not OK) which seems a bit easier to judge, and it may be more manageable if old alerts are deleted.

I think after a couple iterations of this we could decide on some good-ish thresholds, and possibly file separate bugs for proposed improvements to grouping? (Note I have one quick proposed change to the grouping rule from before: #1624).

**Comment by anniesullie** [comment] 2015-10-27 19:38
I was actually thinking that we would do irregular day-long "shifts" where the process is:

1. Delete* all untriaged alerts older than 24 hours, so that you'll be triaging about as many alerts as a regular sheriff would.
2. File 4 new bugs (alerting too sensitive, tests too noisy, poor grouping, lgtm)
3. Triage the alerts into those 4 bugs as well as possible (I agree there will be some overlap)

At this point, we have 4 group_report pages that represent the quality of our current system over a single day's sheriffing.

You can look at the group_report page for the over-sensitive alerts to see how many there are and inspect them all individually, tuning config in the debugger as you go. Then you note the changes you made to the config in the bug. You can compare to the group_report from last time to see if it's improved since the previous tuning.

You can look at the group_report page for noisy tests and ensure there is an issue filed for the specific test. Depending on how many there are, we could work with test owners to fix the noise on them individually, disable monitoring, or blacklist them from non-averaged alerting when we switch over.

After ~10 "shifts", I think we will either get to a point where we think the quality is good enough to switch over (maybe with a few blacklisted exceptions), or where we know there are some specific technical changes we need to make to switch over.

*I actually think auto-triaging the "deleted" alerts to a predefined "not looked at" bug id is probably the way to go. That way, when we are ready to switch to the per-page alerting, we can go back and look at the worst regressions detected by the current system, and make sure they were all caught.

**Comment by qyearsley** [comment] 2015-10-27 19:49
Alright, let's try it :-) I'll try a shift starting from now, and put notes in this doc: [Experimental per-page sheriff rotation](https://docs.google.com/document/d/1QMCZ1KcNXJ1nL52Zc9lhU5btNkLOA1rzaJRX2znD5io/edit#)

Note that [the doc above](https://docs.google.com/document/d/1vywTutgDkbdgtA5eBqrh8fzBCJNERsNFTLMPNQ-xaDo/edit#) in the first comment is proposing a change to `find_anomalies.py` etc. -- if we find that monitoring all sub-series directly works fine and doesn't increase sheriff load etc., then changes to the way that alerting works may be unnecessary.

**Comment by anniesullie** [comment] 2015-10-27 20:27
Sounds great!

If anyone is interested in doing a sheriffing rotation, please sign up in the doc.

**Comment by chrisphn** [comment] 2015-12-16 22:41
Proposed changes with always monitor all sub-series [doc](https://docs.google.com/a/google.com/document/d/11J1nN8qyJSjY9J6qre4AcwxFPDqLn2K6BeLJK-Tle7Q/edit?usp=sharing)

**Comment by anniesullie** [comment] 2016-07-14 13:14
Closing this since we're doing this gradually.

**Closed by anniesullie** 2016-07-14 13:14 UTC
Labels: Enhancement, Perf Dashboard
