### ISSUE TITLE
EventLogImporter matches all vulcanized traces

### ISSUE THREAD

**Issue by bashi** [catapult-project/catapult#1755] opened 2015-11-10 08:26 UTC
Steps to repro:
1. checkout chromium repository and build chrome_public_apk target
https://www.chromium.org/developers/how-tos/get-the-code
2. run memory.blink_memory_mobile benchmark.
$ tools/perf/run_benchmark --output-format=json --output-dir=~/telemetry-traces --pageset-repeat=1 --browser=android-chromium --device <device> --reset-results  memory.blink_memory_mobile
2. Load 0.html in chrome://tracing

You will see the following warning on the DevTools console:
"Need a trace_event_clock_sync to map realtime to import."

Uploaded sample results:
https://drive.google.com/open?id=0B6NYyLPujP4TQ1Vqd19GaldpX00

@natduca, could you route this to folks who are familiar with importer?

**Comment by natduca** [comment] 2015-11-10 14:47
@petrcermak lemme know if you need help troubleshooting

**Comment by petrcermak** [comment] 2015-11-10 15:39
It turns out that this has nothing to do with memory dumps. The problem is that __<tt>EventLogImporter</tt> matches any vulcanized trace__ (see <tt>EventLogImporter.canImport</tt>) because the vulcanized trace contains event log examples (from event_log_importer.html itself).

The importer has actually been broken for quite a while. Even before <tt>EventLogImporter</tt> was added in fb5fd18 ("Couldn't create an importer for the provided eventData" was thrown beforehand).

I'll try to figure out why <tt>TraceEventImporter</tt> doesn't pick up the data.

**Comment by petrcermak** [comment] 2015-11-10 18:13
On a second thought, __have we ever supported importing a vulcanized trace in Trace Viewer?__ I don't think we intend to do that (or do we?) since you can just load the trace straightaway (rather than through chrome:tracing), i.e. just open _file:///.../0.html_ in your browser.

I suppose it would make sense to show an error dialog explaining what to do when a user tries to load a vulcanized trace in Trace Viewer (or perhaps automatically redirect the user).

@natduca, @dj2 WDYT?

**Comment by natduca** [comment] 2015-11-10 18:58
Yes we always have supported importing vulcanized traces. TraceEventImporter has a specific check for this.

**Comment by petrcermak** [comment] 2015-11-10 19:54
OK, I know what the problem is. __<tt>Trace2HTMLImporter</tt>__ works perfectly fine (it can correctly import 0.html), but it __is preceded by <tt>EventLogImporter</tt> in the list of importers__:

<tt>["EmptyImporter", "GcloudTraceImporter", __"EventLogImporter"__, "BattorImporter", "DdmsImporter", "LinuxPerfImporter", "TraceEventImporter", "GzipImporter", "ZipImporter", "V8LogImporter", "EtwImporter", __"Trace2HTMLImporter"__]</tt>

Two possible solutions come into mind:

  1. Give higher priority to <tt>Trace2HTMLImporter</tt>.
  2. Check that the trace does _not_ start with "<!DOCTYPE html>" in <tt>EventLogImporter</tt>.

**Comment by natduca** [comment] 2015-11-10 19:57
2 sounds good. Is EventLogImporter's check too broad? Can we narrow it a bit so that it doesn't eat everything by default?

**Comment by petrcermak** [comment] 2015-11-10 20:04
I don't know the format specification, so I don't know if it could be narrowed down. Right now, <tt>EventLogImporter</tt> simply matches the examples in its own file (event_log_importer.html).

@martijncoenen: Any thoughts on this? Could the event log activity regular expression be narrowed down (e.g. to match at the beginning of line only)?

In the meanwhile, I'll implement 2.

**Comment by natduca** [comment] 2015-11-10 20:22
@petrcermak that makes sense, fix the fire then we can deal with the rest when we get overlap with @martijncoenen's timezone

**Comment by petrcermak** [comment] 2015-11-10 20:44
The issue is now __fixed__. Reassigning further <tt>EventLogImporter</tt> work to @martijncoenen.

**Comment by natduca** [comment] 2015-11-10 23:41
@petrcermak i think better to close this, file a fresh bug with your specific request for @martijncoenen . Bugs where someone has to read the whole bug history and patch codereview history are usually doomed to fail because the ask to the new assignee is higher than just "please fix X"

**Comment by petrcermak** [comment] 2015-11-11 01:08
Good point. Done (#1767).

**Closed by petrcermak** 2015-11-11 01:08 UTC
Labels: Trace Viewer
