### ISSUE TITLE
Chart slider not shown

### ISSUE THREAD

**Issue by camillobruni** [catapult-project/catapult#3565] opened 2017-05-18 06:54 UTC
On many of the V8 RCS graphs we no longer see the chart sliders.

Example links:
- https://chromeperf.appspot.com/report?sid=b22d91217ee3ed5a934cb313faeba75904e26dec76f7845df109a98f7175ec05
- https://chromeperf.appspot.com/report?sid=dba96fd22f281de216b6a22246c1a1621446c7746c828ee7db48a95337a15b97

**Comment by anniesullie** [comment] 2017-05-18 13:07
I'm seeing this too. @benshayden

**Comment by benshayden** [comment] 2017-05-18 19:38
[Dev instance with logging](https://dev-benjhayden-cad45329-dot-chromeperf.appspot.com/report?sid=b22d91217ee3ed5a934cb313faeba75904e26dec76f7845df109a98f7175ec05)

chart-container.updateSlider expects to find `this.seriesGroupList[0].tests[0].path`, but some `tests[i]` don't have `path` fields, just name and selected. It looks like updateSeriesGroup populates the path fields after updateSlider is called.

@eakuefner Is there a missing await? Or should updateSlider return early if path is unset, and wait for updateSeriesGroup to call it again?

**Comment by eakuefner** [comment] 2017-05-18 20:11
Oops, looks like we might just be missing a `path: selectedPath` [here](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/chart-container.html#L734)

**Comment by benshayden** [comment] 2017-05-18 21:13
That didn't work.
Looks like maybe a problem with legacy page state in report-page.

**Comment by camillobruni** [comment] 2017-05-29 14:06
Yes, it seems to happen only with old reports, new reports have the chart slider.

**Comment by camillobruni** [comment] 2017-06-01 09:26
Is there anything we can do on our side to improve this?
Is there a possibility to create the reports again?

We heavily rely on reports to navigate our complex RCS benchmarks, recreating the manually again would take quite some time.

**Comment by benshayden** [comment] 2017-06-01 22:07
Sorry! The current version of the dashboard was deployed a few hours before the fix was committed.
Just confirmed that the fix works and deploying a new version with the fix now.

**Comment by camillobruni** [comment] 2017-06-19 21:25
We're still (not) seeing chart sliders on our internal links: 

Examples:
 - https://chromeperf.appspot.com/report?sid=b22d91217ee3ed5a934cb313faeba75904e26dec76f7845df109a98f7175ec05
 - https://chromeperf.appspot.com/report?sid=c783cddd83b7118ee1bd79d400e25061fd3af2f179ab8a19bb095a0cb0c28c9b&start_rev=36637&end_rev=10000000

Is there anything we can from our side to mitigate this issue?

**Comment by benshayden** [comment] 2017-06-20 15:58
Sorry, we're working on [relanding the fix](https://codereview.chromium.org/2920383003). It's turned out to be more complicated than we'd thought.

**Comment by simonhatch** [comment] 2017-09-19 19:37
Pretty sure this is fixed.

**Closed by simonhatch** 2017-09-19 19:37 UTC
Labels: Perf Dashboard
