### ISSUE TITLE
Perf dashboard does not always kick off a bisect when a new bug is filed

### ISSUE THREAD

**Issue by anniesullie** [catapult-project/catapult#2971] opened 2016-11-04 15:52 UTC
Examples from @primiano's recent shift. cc-ing him in case there are questions about how bugs were filed and he is able to remember.
http://crbug.com/661950
http://crbug.com/661948
http://crbug.com/661939
http://crbug.com/661934
http://crbug.com/661932
http://crbug.com/661931
http://crbug.com/661490

@eakuefner can you poke at this? I think the place to start is adding some logging in https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/file_bug.py#L154

**Comment by eakuefner** [comment] 2016-11-29 18:14
Okay, basically the only way I've been able to make any headway here so far has been to scrub the logs after adding my logging above.

Broadly, it seems like bisects fail to kick for two reasons: auto_bisect either couldn't find a metric or couldn't find a bot.

Here's an example from @benhenry's recent shift: https://bugs.chromium.org/p/chromium/issues/detail?id=669563 that shows in the logs as a couldn't find bot, and I think this is a case where we don't have an entry in the map for this one.

I'm a little troubled by my inability to find any entries like the ones Primiano lists that involve chromium.perf bots that clearly have bisectors available and are trying to bisect on a seemingly "normal"  metric.

@anniesullie WDYT about having the dashboard comment on bugs for which bisects could NOT be kicked, with a reason why? That would help us tremendously to link specific bugs that had issues with what went wrong in that specific case, and give us a lot more data about failure modes.

**Comment by eakuefner** [comment] 2016-11-29 18:42
Okay, upon further investigation, all of the cases Primiano linked seem to entirely boil down to one of two causes, the first of which is for sure a problem:

1. Some bisectors (especially for internal bots) are delimited by dashes (-) instead of underscores (_). The code that tries to find a bisector specifically uses "does this name have an underscore in it" to attempt to decide whether a bot name belongs to a bisector or not: https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/auto_bisect.py#L167 which is a flawed heuristic given this fact.
2. Some bots may have slightly different names than are listed in the bot map. I think that may explain cases like https://bugs.chromium.org/p/chromium/issues/detail?id=661932 and https://bugs.chromium.org/p/chromium/issues/detail?id=661931 but I'm still investigating.

**Comment by anniesullie** [comment] 2016-11-29 18:57
I think it would be great to always comment on the bug when the bisect cannot be kicked. We might need to do some small bit of special casing, such as only adding this comment if the alert is on a master that has *any* bisectors.

**Comment by eakuefner** [comment] 2016-11-29 18:58
I think that might be the easiest way to make progress on case 2 (since the reasoning I listed doesn't seem to hold exactly)

**Comment by anniesullie** [comment] 2017-01-03 16:14
Just saw a ton of these coming back from the holidays:
https://bugs.chromium.org/p/chromium/issues/detail?id=677413
https://chromeperf.appspot.com/group_report?bug_id=677414
https://bugs.chromium.org/p/chromium/issues/detail?id=677419
https://bugs.chromium.org/p/chromium/issues/detail?id=677424
https://bugs.chromium.org/p/chromium/issues/detail?id=677433
https://bugs.chromium.org/p/chromium/issues/detail?id=677451
https://bugs.chromium.org/p/chromium/issues/detail?id=677453
https://bugs.chromium.org/p/chromium/issues/detail?id=677460
https://chromeperf.appspot.com/group_report?bug_id=677461
https://chromeperf.appspot.com/group_report?bug_id=677462
https://chromeperf.appspot.com/group_report?bug_id=677463
https://chromeperf.appspot.com/group_report?bug_id=677464
https://chromeperf.appspot.com/group_report?bug_id=677466

**Comment by anniesullie** [comment] 2017-01-05 20:31
Note: I get an error on the perf dashboard when I file a bug on an internal perfbot, saying it could not choose a bisect bot. But when I kick it off manually, it works fine. See https://bugs.chromium.org/p/chromium/issues/detail?id=678733 for an example where this happened.

@simonhatch do you have any cycles to look into automatically kicking bisects on internal perfbots? I think there are multiple bugs here, but that part is pretty high priority.

**Comment by simonhatch** [comment] 2017-01-05 22:37
Yeah I can look into this

**Comment by simonhatch** [comment] 2017-01-06 22:51
So one of the other issues seems to be when we have a bunch of grouped alerts with non-overlapping ranges. The dashboard tries to minimize the bisect range and with non-overlapping ranges we can end up with an invalid range where good > bad. I think if we want to be conservative, we should just use the range specified by the anomaly we're choosing to test from. That way you can be more confident the regression actually occurs in that range. Fiddling with the range assumes that all other tests have the same root cause.

**Comment by anniesullie** [comment] 2017-01-06 22:57
I agree, we should bisect on the range specified by the anomaly, it's definitely possible the other tests don't have the same root cause.

**Comment by simonhatch** [comment] 2017-01-10 17:43
Wrote a quick script to scrape for issues filed from the dashboard, checks the 2nd comment is the graphs link and that there's a 3rd comment with the bisect. So far no new issues have been filed without a bisect, I can check back in a week or 2 and close this.

**Comment by eakuefner** [comment] 2017-02-16 22:19
Simon, it seems like this bug is ready to close. Feel free to reopen if not.

**Closed by eakuefner** 2017-02-16 22:19 UTC
Labels: Bisect, Bug, Perf Dashboard
