### ISSUE TITLE
[📍] Pinpoint fails to load the graph on first load

### ISSUE THREAD

**Issue by majido** [catapult-project/catapult#4204] opened 2018-01-26 18:04 UTC
Opening any pinpoint bisect result pages does not show the graph on first load. Here is one case for example: https://pinpoint-dot-chromeperf.appspot.com/job/16e8e75c840000

Refreshing the page fixes the issue.

I also see the following error in console:

    Uncaught Error: Invalid dimensions for plot, width = 0, height = 240
    at Canvas.resize (jquery.flot.min.js:7)
    at new Canvas (jquery.flot.min.js:7)
    at setupCanvases (jquery.flot.min.js:7)
    at new Plot (jquery.flot.min.js:7)
    at Function.$.plot (jquery.flot.min.js:8)
    at HTMLElement.draw (job-chart.html:170)
    at polymer.html:1314

**Comment by simonhatch** [comment] 2018-01-26 18:10
@dave-2

**Comment by dave-2** [comment] 2018-01-26 18:12
Duplicate of #4031

**Closed by dave-2** 2018-01-26 18:12 UTC
Labels: Bisect
