### ISSUE TITLE
[📍] Cannot create a perf job with extra test arguments

### ISSUE THREAD

**Issue by sanekspot** [catapult-project/catapult#4252] opened 2018-02-13 10:00 UTC
I was following the steps from https://chromium.googlesource.com/chromium/src/+/master/docs/speed/perf_trybots.md.
I was able to successfully run a job without extra arguments. However, if I add `--extra-chrome-categories="browser,netlog"` to the "Extra Test Arguments" field without modifying all other fields, I get redirected to the undefined page with the error message "Invalid job id."

I could run the same job with the `run_benchmark.py try` script before. I'd also like to have more meaningful error message in case incorrect arguments were provided.

**Comment by simonhatch** [comment] 2018-02-13 17:15
Believe this is a duplicate of #4130

**Closed by simonhatch** 2018-02-13 17:15 UTC
Labels: Bisect
