### ISSUE TITLE
Dashboard API alert history returns same values regardless if time duration given

### ISSUE THREAD

**Issue by randalnephew** [catapult-project/catapult#3924] opened 2017-09-27 19:18 UTC
Using my code in: https://codereview.chromium.org/3014653002/

alert_analyzer.py --credentials $HOME/soundwave/creds.json --benchmark system_health.memory_desktop --days=300
Making API request: alerts/history/300/?benchmark=system_health.memory_desktop
52 alerts found! Collecting data related to them...

alert_analyzer.py --credentials $HOME/soundwave/creds.json --benchmark system_health.memory_desktop --days=1
Making API request: alerts/history/1/?benchmark=system_health.memory_desktop
52 alerts found! Collecting data related to them...

alert_analyzer.py --credentials $HOME/soundwave/creds.json --benchmark system_health.memory_desktop --days=30
Making API request: alerts/history/30/?benchmark=system_health.memory_desktop
52 alerts found! Collecting data related to them...

alert_analyzer.py --credentials $HOME/soundwave/creds.json --benchmark system_health.memory_desktop --days=0
Making API request: alerts/history/0/?benchmark=system_health.memory_desktop
52 alerts found! Collecting data related to them...

alert_analyzer.py --credentials $HOME/soundwave/creds.json --benchmark system_health.memory_desktop --days=-1
Making API request: alerts/history/-1/?benchmark=system_health.memory_desktop
52 alerts found! Collecting data related to them...

@anniesullie 
@simonhatch

**Comment by randalnephew** [comment] 2017-09-27 19:51
Meant to put some of the alert data into this as well:
      "absolute_delta": "1280930.666667",
      "bisect_status": null,
      "bot": "chromium-rel-mac12",
      "bug_id": 690042,
      "dashboard_link": "/report?masters=ChromiumPerf&bots=chromium-rel-mac12&tests=system_health.memory_desktop%2Fmemory%3Achrome%3Aall_processes%3Areported_by_chrome%3Amalloc%3Aeffective_size_avg%2Fload_search%2Fload_search_yahoo&checked=load_search_yahoo%2Cload_search_yahoo_ref%2Cref&rev=502854", 
      "date": "2017-09-27",
      "display_end": null,
      "display_start": null,
      "end_revision": 502854,
      "group": "agxzfmNocm9tZXBlcmZyFwsSCkFsZXJ0R3JvdXAYgIDgg8LqpwoM",
      "improvement": false,
      "key": "agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDg4577tQoM",
      "master": "ChromiumPerf",
      "median_after_anomaly": 26909305.333333336,
      "median_before_anomaly": 25628374.666666664,
      "percent_changed": "5.0%",
      "recovered": false,
      "ref_test": "ChromiumPerf/chromium-rel-mac12/system_health.memory_desktop/memory:chrome:all_processes:reported_by_chrome:malloc:effective_size_avg/load_search/load_search_yahoo_ref", 
      "start_revision": 502818,
      "test": "memory:chrome:all_processes:reported_by_chrome:malloc:effective_size_avg/load_search/load_search_yahoo", 
      "testsuite": "system_health.memory_desktop",
      "timestamp": "2017-09-27T12:43:57.934750",
      "type": "anomaly",
      "units": "sizeInBytes"


      "absolute_delta": "931901.000000",
      "bisect_status": null,
      "bot": "chromium-rel-win10",
      "bug_id": 690042,
      "dashboard_link": "/report?masters=ChromiumPerf&bots=chromium-rel-win10&tests=system_health.memory_desktop%2Fmemory%3Achrome%3Aall_processes%3Areported_by_chrome%3Amalloc%3Aeffective_size_avg%2Fload_media%2Fload_media_dailymotion&checked=load_media_dailymotion%2Cload_media_dailymotion_ref%2Cref&rev=502822", 
      "date": "2017-09-26",
      "display_end": null,
      "display_start": null,
      "end_revision": 502822,
      "group": "agxzfmNocm9tZXBlcmZyFwsSCkFsZXJ0R3JvdXAYgIDgg8LqpwoM",
      "improvement": false,
      "key": "agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDgo4WRvgsM",
      "master": "ChromiumPerf",
      "median_after_anomaly": 18190017.0,
      "median_before_anomaly": 17258116.0,
      "percent_changed": "5.4%",
      "recovered": false,
      "ref_test": "ChromiumPerf/chromium-rel-win10/system_health.memory_desktop/memory:chrome:all_processes:reported_by_chrome:malloc:effective_size_avg/load_media/load_media_dailymotion_ref", 
      "start_revision": 502791,
      "test": "memory:chrome:all_processes:reported_by_chrome:malloc:effective_size_avg/load_media/load_media_dailymotion", 
      "testsuite": "system_health.memory_desktop",
      "timestamp": "2017-09-26T00:30:46.078940",
      "type": "anomaly",
      "units": "sizeInBytes"

      "absolute_delta": "1083360.000000",
      "bisect_status": null,
      "bot": "chromium-rel-mac12",
      "bug_id": 767243,
      "dashboard_link": "/report?masters=ChromiumPerf&bots=chromium-rel-mac12&tests=system_health.memory_desktop%2Fmemory%3Achrome%3Aall_processes%3Areported_by_chrome%3Amalloc%3Aeffective_size_avg%2Fload_search%2Fload_search_google&checked=load_search_google%2Cload_search_google_ref%2Cref&rev=502854", 
      "date": "2017-09-25",
      "display_end": null,
      "display_start": null,
      "end_revision": 502854,
      "group": "agxzfmNocm9tZXBlcmZyFwsSCkFsZXJ0R3JvdXAYgIDgg8LqpwoM",
      "improvement": false,
      "key": "agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDgw5ffvQkM",
      "master": "ChromiumPerf",
      "median_after_anomaly": 26701443.333333336,
      "median_before_anomaly": 25618083.333333332,
      "percent_changed": "4.2%",
      "recovered": false,
      "ref_test": "ChromiumPerf/chromium-rel-mac12/system_health.memory_desktop/memory:chrome:all_processes:reported_by_chrome:malloc:effective_size_avg/load_search/load_search_google_ref", 
      "start_revision": 502818,
      "test": "memory:chrome:all_processes:reported_by_chrome:malloc:effective_size_avg/load_search/load_search_google", 
      "testsuite": "system_health.memory_desktop",
      "timestamp": "2017-09-25T03:17:08.098840",
      "type": "anomaly",
      "units": "sizeInBytes"


On the third one the date field is:  2017-09-25
which means we would expect to find it on the --days=30 run, but not on the --days=1 run.

**Comment by randalnephew** [comment] 2017-09-27 19:55
List of all dates:
      "date": "2017-09-27", 
      "date": "2017-09-26", 
      "date": "2017-09-25", 
      "date": "2017-09-25", 
      "date": "2017-09-25", 
      "date": "2017-09-23", 
      "date": "2017-09-23", 
      "date": "2017-09-23", 
      "date": "2017-09-22", 
      "date": "2017-09-22", 
      "date": "2017-09-22", 
      "date": "2017-09-22", 
      "date": "2017-09-21", 
      "date": "2017-09-21", 
      "date": "2017-09-21", 
      "date": "2017-09-21", 
      "date": "2017-09-21", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 
      "date": "2017-09-20", 

The oldest one is 7 days old, and 7 is the default.

**Comment by anniesullie** [comment] 2017-09-27 22:48
The problem is the trailing slash at the end of the path. This defaults to 7:

`alerts/history/300/?benchmark=system_health.memory_desktop`

This correctly parses as 300:

`alerts/history/300?benchmark=system_health.memory_desktop`

I'm going to WontFix since there's a pretty simple change to fix the API call, even though the error from the dashboard is not ideal.

**Closed by anniesullie** 2017-09-27 22:48 UTC
Labels: Perf Dashboard

**Comment by randalnephew** [comment] 2017-09-27 23:18
Confirming that fixed the problem in my tool. 
/, the new ;.
