### ISSUE TITLE
[trace-viewer/systrace] Vsync highlighting doesn't work in Android API 23 platform-tools systrace

### ISSUE THREAD

**Issue by astreet** [catapult-project/catapult#1747] opened 2015-11-06 21:47 UTC
This used to work but doesn't seem to work anymore. Instead I see little F's in circles, presumably where the frame boundaries are which is much less useful than zebra-stripe highlighting.

Code I ran: `systrace/systrace.py --time=10 -o trace.html sched gfx view wm`
What I see (with 'highlight vsync' checked):

![screen shot 2015-11-06 at 1 46 01 pm](https://cloud.githubusercontent.com/assets/594924/11009577/d3497930-848c-11e5-826f-ce70870e3669.png)

**Comment by natduca** [comment] 2015-11-09 23:48
@ChrisCraik @charliea any ideas?

**Comment by zeptonaut** [comment] 2015-11-09 23:56
Hmmmm, I'm not sure. @ChrisCraik, can you check to see if this is Android-specific? I just recorded a trace in Chrome and the highlighter seems to be working fine.

![image](https://cloud.githubusercontent.com/assets/1407397/11050400/60a55adc-86fa-11e5-9699-0c90d0e5cd31.png)

**Comment by natduca** [comment] 2015-11-10 04:25
I think we should ask @astreet for an attached trace, or if he can't send it publically, then for him to email it to one of us. Charlie, since vsync highlighter is in our codebase but kinda weirdly tested, I think its our job to keep it working.... so I think once we have a trace file, we'd be best off figuring it out ourselves. Over time we can figure out what @ChrisCraik is responsible for...

**Comment by astreet** [comment] 2015-11-10 14:27
Here's a copy of my trace: http://www78.zippyshare.com/v/RjpLjUOV/file.html

**Comment by zeptonaut** [comment] 2015-11-10 22:58
Agreed - I think that looking directly at the trace (thanks @astreet!) is the best idea.

Sorry, I wasn't trying to suggest that it wasn't our response to keep it working. One possible explanation for this behavior is that Android stopped issuing the trace events used to mark vsyncs, and I wasn't sure if Chris might know something about that.

**Comment by zeptonaut** [comment] 2015-11-10 23:45
Actually, never mind. He mentioned that we're getting the "F" circles still that mark the start of new frames, so this isn't likely the cause.

**Comment by zeptonaut** [comment] 2015-11-10 23:54
It actually looks like the "F" circles and the vertical sync stripes are powered by two separate things.
The "F" circles are powered by [this](https://github.com/catapult-project/catapult/blob/2091404475cbba9b786442979b6ec631305275a6/tracing/tracing/extras/android/android_app.html#L277-L285), and the vertical sync stripes are powered by [this](https://github.com/catapult-project/catapult/blob/2091404475cbba9b786442979b6ec631305275a6/tracing/tracing/extras/vsync/vsync_auditor.html#L15-L31).

I haven't had the time to follow those code paths all the way through, but it seems like a possible source of bugs that the two sources of threads are driven by completely separate trace analyses.

**Comment by nico1510** [comment] 2017-05-05 13:05
is there a solution for this ? I'm seeing the same problem

**Comment by natduca** [comment] 2017-05-08 16:58
@ChrisCraik

**Comment by ChrisCraik** [comment] 2017-05-08 18:21
If you're seeing this problem recently, are you tracing with the gfx tag? That tag is on by default if you don't specify tags.

Also note that your device must be drawing to produce vsync events - SurfaceFlinger will only toggle vsync if it is pushing frames, so a window must be visible and actively updating for the events to be generated.

Android hasn't changed how it traces these events (VSYNC-app counter in the SurfaceFlinger process), and toggling the vsync tracing still works for me. I'd be happy to look at a trace - it looks like the one from astreet's comment above is no longer available.

**Comment by nico1510** [comment] 2017-05-08 19:58
I got it working by launching systrace via Android Device Monitor :) I would close the issue but I'm not the creator..

**Comment by ChrisCraik** [comment] 2017-05-08 20:07
Good to hear, I'll close on assumption it's missing the gfx tag or frames being drawn.

**Closed by ChrisCraik** 2017-05-08 20:07 UTC
Labels: Bug, P1, Trace Viewing
