### ISSUE TITLE
Error: Couldn't create an importer for the provided eventData

### ISSUE THREAD

**Issue by ianvollick** [catapult-project/catapult#2378] opened 2016-06-01 18:38 UTC
Hitting an error on Chrome 50 importing a large Frame Viewer trace:

Error: Couldn't create an importer for the provided eventData.
    at Object.Import.createImporter_ (chrome://tracing/tracing.js:879:3342)
    at Object.createImports (chrome://tracing/tracing.js:875:21)
    at Object.Task.run (chrome://tracing/tracing.js:1048:13)
    at runAnother (chrome://tracing/tracing.js:1060:136)
    at runTask (chrome://tracing/tracing.js:1023:57)
    at processIdleWork (chrome://tracing/tracing.js:1029:116)
    at chrome://tracing/tracing.js:1017:81

**Comment by petrcermak** [comment] 2016-06-06 12:13
Could you please provide more details about the trace? How long you were recording for, which tracing categories were enabled, how many tabs did you have open and what URLs, did you use any special compile-/run-time flags, did this happen right after you stopped recording, ...

**Comment by ianvollick** [comment] 2016-06-09 13:13
I just hit this again tracing a google spreadsheet. I recorded a Frame Viewer trace (no special categories), I had only two tabs open, the sheet and docs. I did have devtools open. No special flags, I was running vanilla stable.

**Comment by petrcermak** [comment] 2016-06-10 18:04
Thanks for the steps. The problem is that the base64-encoded tracing data (from <tt>/json/end_recording_compressed</tt>) __doesn't make it to Trace Viewer__ at all: the <tt>data</tt> string on [this line](https://github.com/catapult-project/catapult/blob/master/tracing/tracing/ui/extras/about_tracing/xhr_based_tracing_controller_client.html#L96) is empty. I got another failure already with 20% trace buffer usage: _"Inflated gzip data too long to fit into a string (307052987)."_

I suspect that both of these failures are due to the maximum string length imposed by V8. I don't think we'll be able to fix this until [Tracing V2](bit.ly/TracingV2) is implemented. Furthermore, we'll probably need some sort of streaming here because we seem to be hitting the limits of XHR.

@primiano, @vinterstum, @natduca: FYI

**Comment by zeptonaut** [comment] 2016-07-22 15:30
I'm also seeing this on Canary (54.0.2802.2 (Official Build) canary (64-bit)). Here's the trace:

[trace_trace (1).json.gz](https://github.com/catapult-project/catapult/files/378518/trace_trace.1.json.gz)

When I decompress that trace with `gunzip trace_trace\ \(1\).json.gz`, I get the following error:

```
gunzip: /Users/charliea/Downloads/trace_trace (1).json.gz: unexpected end of file
gunzip: /Users/charliea/Downloads/trace_trace (1).json.gz: uncompress failed
```

So it looks like whatever we're recording isn't a valid gzip file. I'm going to confirm that trace viewer is failing at the same place by setting a breakpoint in `zip_importer.html`.

**Comment by zeptonaut** [comment] 2016-07-22 15:41
Going to do some initial investigation into this. It looks like the gzip inflation in trace viewer is working, so maybe I'm just not using the right command line arguments when I do it manually. I'm seeing a successful gzip inflation followed by a failed import. Still looking into it.

**Comment by zeptonaut** [comment] 2016-07-22 15:47
I'm actually going to unassign this from myself and split this investigation back into #2529, now that it's clear that the issue I'm having isn't related to buffer size limits.

**Comment by zeptonaut** [comment] 2016-12-08 16:33
Closing this due to no action in the last 6 months.

**Closed by zeptonaut** 2016-12-08 16:33 UTC
Labels: Bug, OOM, Trace Viewing

**Comment by vovandaihai** [comment] 2017-04-12 04:57
Thanks, i had set trace buffer size and success!
