### ISSUE TITLE
[IR] Too many loads in the IR

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#1298] opened 2015-08-20 17:50 UTC
Too many loads shows up in a trace, it does not work for the analysis.

A load IR should represent what the user perceives as loading.

@paulirish can you upload the example trace?

**Comment by natduca** [comment] 2015-08-20 18:10
Paul, plz reassign to @fmeawad when sorted

**Comment by benshayden** [comment] 2015-08-31 22:10
I suspect that some of the Load IRs might be caused by iframes. I was hoping to be able to label Load IRs according to whether they belong to the main frame or iframes, so that you could filter based on that label. That might require adding flow events and other annotations to chrome and blink.
Does that sound like it should address this issue?

**Comment by dj2** [comment] 2015-09-09 19:01
@paulirish is there an example trace we can look at to see the load issue?

**Comment by chiniforooshan** [comment] 2015-09-10 13:22
desktop/sfgate_v8_samples.json.gz from measurmt-traces has many overlapping load events.

**Comment by dj2** [comment] 2015-09-10 15:17
Passing over to @fmeawad as we have a tracing showing the issue.

**Comment by natduca** [comment] 2015-09-22 18:58
@benshayden can we route to you for resolution? Feel free to reassign as needed...

**Comment by benshayden** [comment] 2015-10-06 23:16
Please read patiently. Two questions for whoever has opinions at the end.

I recently added a trace event RenderFrameImpl::createChildFrame that links child frames with their parent frames. Now I'm making RAILIRFinder use that trace event to name Load IRs either "MainFrame" or "Subframe": https://codereview.chromium.org/1391723002

Traces collected before the createChildFrame trace event was added cannot be fixed.

Traces could be timed so that they miss the createChildFrame event, so Loads that are actually for subframes could mistakenly be marked MainFrame. In order to fix this, I'm planning on snapshotting the FrameTree using TRACE_EVENT_OBJECT_SNAPSHOT_WITH_ID, so that Loads and whatever else can look for their routing id in the current FrameTree, or other new trace events could use their frame tree node id or correlate other ids with frame tree node ids.

Should Subframe Loads be hidden from the Interactions track view? Or turned a different color? Or swallowed in RAILIRFinder?

Should about:blank Loads be dropped?

**Comment by natduca** [comment] 2015-10-08 04:30
I left some comments on https://codereview.chromium.org/1391723002/#msg9 ... these are great questions! If this keeps confusing us, it might be time for a doc with pictures that list out the corner cases to help us all figure this space out. This is clearly tough stuff!

**Comment by benshayden** [comment] 2015-10-27 22:42
In "Drop subframe LoadIRs", Nat asked how this might be done for traces that don't contain createChildFrame events.

There's an instant event titled "LoadFinished" under the "RenderFrameImpl::didFinishLoad" event. The LoadFinished event is only emitted if the render frame is a main frame.

https://code.google.com/p/chromium/codesearch#chromium/src/content/renderer/render_frame_impl.cc&q=LoadFinished&sq=package:chromium

Until recently, the LoadFinished event was only in the "WebCore" category. It was recently added to the benchmark category, shortly after the createChildFrame trace event was added.

To summarize: if a trace contains the WebCore category (which I believe deep reports should, since it matches '*'; I'll have to check about slow reports), then a rendering (non-startup) Load IR is a main frame Load IR if and only if its corresponding didFinishLoad event contains a LoadFinished instant event.

It should be impossible for a Load IR to contain both a createChildFrame event and a LoadFinished event. This case might be a candidate for an importWarning, either visible or not.

Should a rendering Load be considered a main frame Load if there is neither a createChildFrame event nor a LoadFinished event? The answer to that question might depend on whether there's a way to know if WebCore was in the category filter. If WebCore was in the category filter and there is no LoadFinished event, then it was a subframe Load. If WebCore was not in the category filter, or if there is no way to know whether WebCore was in the category filter, and there was no createChildFrame event then I think we would need to assume that it was a main frame Load, for the same reason that  "Drop subframe Load IRs" currently considers such Loads to be main frame.

Thoughts?

**Comment by benshayden** [comment] 2015-11-14 00:23
I think I've solved this as much as possible for now.

We're planning on tracing FrameTrees and using those to more reliably find main frame loads.
https://code.google.com/p/chromium/issues/detail?id=537802
https://github.com/catapult-project/catapult/issues/1663

**Closed by benshayden** 2015-11-14 00:23 UTC
Labels: RAIL, Trace Viewer
