### ISSUE TITLE
[Results2] Allow increasing the width of the metric name column

### ISSUE THREAD

**Issue by ulan** [catapult-project/catapult#2979] opened 2016-11-07 15:23 UTC
Currently metric names are cropped if they are too long. This makes the some results unreadable (see screeenshot).

![screenshot from 2016-11-07 16 19 18](https://cloud.githubusercontent.com/assets/294429/20063088/3f3594b8-a506-11e6-9850-17cd0d7e4c3c.png)

**Comment by anniesullie** [comment] 2016-11-07 15:25
@benshayden is this a dupe of #2946 ?

**Comment by eakuefner** [comment] 2016-11-07 17:29
@anniesullie Whoops, yes it is.

**Closed by eakuefner** 2016-11-07 17:29 UTC
Labels: Hotlist:v8, Results2
