### ISSUE TITLE
Design battor based power metrics

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2087] opened 2016-03-01 16:45 UTC
We need to design battor based power metrics.
@zeptonaut @wangzhen127 @aschulm

**Comment by nedn** [comment] 2016-03-01 18:51
Work in progress doc: https://docs.google.com/document/d/10-ZoMLw_g-RvWxalXjTi-RzfaUdyOWVnKcqB390xHCQ/edit#

**Comment by eakuefner** [comment] 2016-05-17 18:24
This is a dupe of #2309

**Closed by eakuefner** 2016-05-17 18:24 UTC
Labels: System Health, Telemetry
