### ISSUE TITLE
Perf Dashboard: Alters disappear from the dashboard UI when sorting

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#2541] opened 2016-07-26 09:58 UTC
Chrome version: 53.0.2785.8 (Linux)
URL: https://chromeperf.appspot.com/alerts?sortby=bot&sortdirection=down

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
None seen.

Please describe the problem:
When I just open https://chromeperf.appspot.com/alerts?sortby=bot&sortdirection=down I see 82 alerts.
If I click on any of the columns, they get sorted, but the number of alerts reduces drastically (down to ~20) There seems to be some UI bug here.

**Comment by anniesullie** [comment] 2016-07-26 12:13
This is a dupe of #2272. Sorry the UI is such a mess. @Apeliotes will be doing a lot of improvements in Q3.

**Closed by anniesullie** 2016-07-26 12:13 UTC
Labels: Perf Dashboard
