### ISSUE TITLE
[Pinpoint] Pinpoint is not automatically assigning bugs if culprit is found

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#3934] opened 2017-09-29 07:58 UTC
The old bisect script did automatically assigned a bug to an owner when the culprit was found. This seems to be not the case anymore with Pinpoint. See https://bugs.chromium.org/p/chromium/issues/detail?id=769716#c6 as an example.

**Comment by anniesullie** [comment] 2017-09-29 13:40
We also want to cc CL reviewers. This was removed from the old bisect script, but it's come up in recent postmortems, and we've decided it should be added back.

**Comment by simonhatch** [comment] 2017-09-29 15:42
Gonna mark this as a dupe of #3890 

Definitely on our radar as high priority: [bug list](https://docs.google.com/spreadsheets/d/1aB3NyFprp54hXlumR0HZfS3o_eVPJSF7N0qE5DUbC4A/edit#gid=2103056945)

**Closed by simonhatch** 2017-09-29 15:42 UTC
Labels: Bisect
