### ISSUE TITLE
Sorting rows in memory dump details collapses all rows.

### ISSUE THREAD

**Issue by ssiddhartha** [catapult-project/catapult#2276] opened 2016-04-22 17:00 UTC
On Memory-Infra dumps, sorting the details with a column like "size" collapses all rows into top level row. This sort should happen in place.
Note: It recently stopped working.

**Comment by ssiddhartha** [comment] 2016-04-22 17:03
@petrcermak

**Comment by petrcermak** [comment] 2016-05-05 10:38
I bisected the problem and it is due to 19214a3a5aff24f85a779f096b976107cadd2cf6, so I'm assigning this to @benshayden.

How to reproduce:
  1. Open [this test](http://localhost:8003/tracing/tests.html?testFilterString=instantiate_multipleDiff&testSuiteName=tracing.ui.analysis.memory_dump_heap_details_pane_test) _(requires that you run <tt>bin/run_dev_server</tt>)_.
  2. Click on the header of the "Size" column.
  3. Not only are all rows collapsed (non-ergonomic), but their expansion arrows (▶) still indicate that the rows are expanded (wrong).

Please also add a test with the fix. Thanks!

**Comment by petrcermak** [comment] 2016-06-01 13:56
@benshayden: Friendly ping

**Comment by benshayden** [comment] 2016-06-08 17:48
Sorry, just saw this yesterday. Looking now.

**Closed** 2016-10-29 05:42 UTC
Labels: Bug, P1, Trace Viewing
