### ISSUE TITLE
Mismatch between series name in legend and chart

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#2701] opened 2016-08-22 16:04 UTC
See screenshot:

![bad_dashboard](https://cloud.githubusercontent.com/assets/16922344/17861757/42510e60-688a-11e6-9310-9677df3664e6.png)

Not sure if this is just a display issue, or if values from different series have been actually jumbled up. :worried: 

@anniesullie

**Comment by perezju** [comment] 2016-08-22 16:13
I wanted to share a direct link to the dashboard showing the issue, but I've just noted that, copying the url and pasting on a new window *does* show the correct series on both legend and chart. So does look like some display issue only.

To reproduce:

* Go to some dashboard with many subtests: [example](https://chromeperf.appspot.com/report?sid=d90db8ebfff07ecbc18fccbe6df5c4d675a0af2d7a95aa42f98cd372e62d36e5)
* Click to expand list of subtests on legend (e.g. "21 more")
* Deselect the summary series (e.g. "foreground")
* Select some random series (e.g. "http_m_facebook_com_rihanna")
* Dashboard will often show the *wrong* series on the chart (e.g. "https_mobile_twitter_com_justinbieber_skip_interstitial_true")
* Copy the url and paste onto new tab; both chart and legend show the correct series (e.g. "http_m_facebook_com_rihanna").

**Comment by petrcermak** [comment] 2016-08-22 16:14
This is actually a duplicate of #2694, but since you added the extra details, I'll close the other issue instead :wink:

**Comment by pavolas** [comment] 2016-08-30 18:02
If someone who works on this project hadn't told me about this bug, I would have lost many, many hours to it. This has comparable effect to the perf dashboard reporting wrong data. Seems like a P-0 to me. Can we please get this fixed ASAP?

**Comment by anniesullie** [comment] 2016-08-30 18:19
@natduca I think you just hit this as well in #2742.

**Comment by Apeliotes** [comment] 2016-08-30 19:23
I'll look at this today.

**Comment by Apeliotes** [comment] 2016-08-30 23:42
So, it wasn't an issue with how we were displaying it. Turns out that we rely on the legend index matching that of the related json data. I'm reverting a cl that landed 3 weeks ago that alphabetized the legend and writing a new bug on us doing this in a less automagical way.

**Comment by Apeliotes** [comment] 2016-08-30 23:47
New bug: #2747

**Comment by Apeliotes** [comment] 2016-08-31 00:20
New version of Dashboard has been deployed and set as default. Please re-open if you can still see this behavior.

**Closed by Apeliotes** 2016-08-31 00:20 UTC
Labels: Bug, P1, Perf Dashboard
