### ISSUE TITLE
Search results summary missing

### ISSUE THREAD

**Issue by jdduke** [catapult-project/catapult#1190] opened 2015-08-05 21:27 UTC
Lately, searching a trace fails to display any kind of search results summary listing. It'll show how many hits there are in the search box, show you the first hit, and let you navigate between hits, but that's it.  In the good ole days it used to display a results summary at the bottom with a list of all matches. It was incredibly convenient. 

How about restoring it? Or maybe I'm just missing a toggle/buttonpress or two? I first thought the double-right arrow next to the search box would show the results, but that just opens the console.

![no_search_results_summary](https://cloud.githubusercontent.com/assets/479117/9098260/8954b32e-3b7d-11e5-8c61-a7b766b6f18a.png)

**Comment by dj2** [comment] 2015-08-05 23:40
This is a dupe of #1184

**Closed by dj2** 2015-08-05 23:40 UTC
Labels: duplicate
