### ISSUE TITLE
Graphs not loading on Chromeperf

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#2830] opened 2016-09-21 08:21 UTC
Repro:
1.) Open https://chromeperf.appspot.com/report?sid=1be638d9f575cfb937fab7d6ea8c133704cf8b2b1a5929a722ac21baf7cec8ad&start_rev=36493&end_rev=10000000000000
2.) Endless loading

v8.x64 is also not loading and other benchmarks under v8.\* seem to take longer. v8.x64 is the bot with the runtime callstats btw.

@camillobruni @anniesullie @Apeliotes

**Comment by anniesullie** [comment] 2016-09-21 16:54
Looks like this line is taking too long to run:
list_tests.GetSubTests('v8', ['internal.client.v8/x64'])

It memcaches the value, but it takes so long that memcache never gets set, it just times out computing. Looking into whether it can perform better...

**Comment by anniesullie** [comment] 2016-09-21 16:59
Two questions come up:

1. Why do we even call this from /graph_json?
2. Why does it call this twice (once for deprecated and once not)?

**Comment by anniesullie** [comment] 2016-09-21 17:01
@Apeliotes - can you remove the listing of deprecated tests from GetSubTests temporarily and then reassign to me?

**Comment by Apeliotes** [comment] 2016-09-23 00:02
https://chromeperf.appspot.com/report?sid=1be638d9f575cfb937fab7d6ea8c133704cf8b2b1a5929a722ac21baf7cec8ad&start_rev=36493&end_rev=10000000000000

loads in the current default version of dashboard.

The metrics in v8/x64 that I've looked at load, but don't have any of the metrics selected by default. BigNum doesn't seem to have any graphs associated with it. Is this expected?

**Comment by Apeliotes** [comment] 2016-09-23 00:11
Also, removing the listing of deprecated tests didn't help in the demo I setup (https://dev-aiolos-208634c8-dot-chromeperf.appspot.com)

**Comment by camillobruni** [comment] 2016-09-23 13:13
I'm not sure I fully understand what you mean by "have not metrics selected by default".
If that's the thing where no graphs are shown, then no, this is not expected and happens when more than graph would be shown.

As for the dropdowns and report loading, I think we've never been this fast before :)

**Comment by anniesullie** [comment] 2016-09-30 21:50
Related to #2887

**Comment by camillobruni** [comment] 2016-10-28 12:50
This has gotten worse again. We only get a fraction of the graphs up when viewing something like [runtime-stats](https://chromeperf.appspot.com/report?sid=a48dec5066f5d0028667e38d57ca2707ffcacd59b4122b94a99d14d0bc2ad0f6&start_rev=36921&end_rev=10000000).
Even refreshing doesn't seem to help much, and the few graphs that do load take >20s.

**Comment by anniesullie** [comment] 2016-10-28 13:22
I'm really sorry about the hiccups here. I loaded it a few times, and it looks like the cache got filled in and the charts load again. Still need to stabilize the underlying issues, but is it working okay for the time being?

**Comment by camillobruni** [comment] 2016-10-28 13:28
We don't mind the delay, but currently the graphs only load partially, which is quite a drop in usefulness for us.

**Comment by anniesullie** [comment] 2016-10-28 13:30
Right, they were loading partially earlier, but now they are loading fully for me. You are still seeing some of them load partially? Is it consistent which ones?

**Comment by natorion** [comment] 2016-12-21 14:35
We switched on another RuntimeCallstats variant this week. It seems this overloaded the Chromeperf frontend again because v8.x64 is not loading again.

**Comment by natorion** [comment] 2017-01-10 09:46
Gentle ping on this, we still can't open the v8.x64 bot. Not even with predefined reports or forced reloads. It seems a lot of requests get terminated with server error 500.

Example link: https://chromeperf.appspot.com/report?sid=2ad4febd345339895837cd336da371a5d2e7f324493b9af8bb0d9d8110b835ed&start_rev=41000&end_rev=3980500

**Comment by jessimb** [comment] 2017-01-10 17:40
A quick look into this...
The 500s in the console are referring to chart_container's console.warn() (https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/elements/chart-container.html#L744)
This is an error from the POST request to /graph_json. I'm not seeing any errors in the logs from /graph_json, so I'm not sure what is going on there. Furthermore, the graphs began to load for me after a few refreshes.

**Comment by anniesullie** [comment] 2017-01-10 18:33
Root cause is #2887

**Comment by natorion** [comment] 2017-01-10 20:26
Thanks for investigating. Unfortunately nobody I asked on the team (~5 people) could open the page even after several reloads. What can we do as a workaround until the root cause is resolved?

**Comment by anniesullie** [comment] 2017-01-11 17:07
Can someone from v8 team check the graphs on this staging server and see if they work as expected? https://dev-sullivan-8b10e782-dot-chromeperf.appspot.com/report?sid=2ad4febd345339895837cd336da371a5d2e7f324493b9af8bb0d9d8110b835ed&start_rev=41000&end_rev=3980500

**Comment by anniesullie** [comment] 2017-01-11 17:17
Workaround set to default version, longer-term fix still in progress.

**Comment by natorion** [comment] 2017-01-11 18:32
I checked the staging server and it seems to work. Thanks!

**Comment by eakuefner** [comment] 2017-02-06 21:15
Taking this from @Apeliotes since I'm actively working on the longer-term solution for this.

**Comment by natorion** [comment] 2017-02-10 15:04
The problem that we can't open the bit v8.x64 from scratch is still existing. This means we are not able to access the test results for any benchmark we are running on this bot. This is not only impacting the runtime call stats but other benchmarks like Octane or microbenchmarks too.

To reiterate:
1.) Open page to select benchmarks
2.) Select v8.x64
3.) Wait a long time
4.) Loading stops after timeout
5.) No benchmark result of the x64 bot is accessible

**Comment by anniesullie** [comment] 2017-02-10 15:07
@eakuefner will you be able to work on this today?

**Comment by simonhatch** [comment] 2017-02-10 15:10
I'll take this later today after I clear up #3204

**Comment by eakuefner** [comment] 2017-02-10 18:29
Simon and I are taking a look at what's going on together right now, but I do hope to push forward on this today.

**Comment by natorion** [comment] 2017-02-10 18:40
Thanks folks!

Ethan Kuefner <notifications@github.com> schrieb am Fr., 10. Feb. 2017,
19:29:

**Comment by anniesullie** [comment] 2017-02-13 04:43
@simonhatch just landed a patch that should reduce the time to generate the menu to around 20s, which should at least make it work consistently while @eakuefner works on the longer-term speed up of fixing the dependencies on the whole tree of timeseries for each benchmark.

I just deployed the patch to the dashboard, let us know how it goes.

**Comment by natorion** [comment] 2017-02-13 10:46
Thanks, benchmarks are loading now (and results too). It takes ~ 30 seconds on my machine.

**Comment by simonhatch** [comment] 2017-02-13 15:12
I have another cl that should knock 4s off, but this is really worst case and anybody who visits after you the subtest dict should have been cached and it should load up in a few seconds.

**Comment by eakuefner** [comment] 2017-04-17 17:39
This has been fixed the right way, so v8 subtests should now load nearly instantaneously in the picker.

**Closed by eakuefner** 2017-04-17 17:39 UTC
Labels: Hotlist:Perf Dashboard Performance, Perf Dashboard
