### ISSUE TITLE
Battor smoke tests are failing flakily

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2321] opened 2016-05-06 21:51 UTC
https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Windows%20Tryserver

Log

Backtrace:
	GetHandleVerifier [0x00623241+2199238]
	GetHandleVerifier [0x0055DF6B+1391600]
	GetHandleVerifier [0x0044971B+258976]
	GetHandleVerifier [0x004499ED+259698]
	GetHandleVerifier [0x0045886A+320751]
	GetHandleVerifier [0x00458557+319964]
	GetHandleVerifier [0x00462E00+363141]
	GetHandleVerifier [0x00462C1F+362660]
	GetHandleVerifier [0x006F3B03+3053448]
	GetHandleVerifier [0x005E5289+1945358]
	GetHandleVerifier [0x005E2A34+1935033]
	GetHandleVerifier [0x005E31BD+1936962]
	GetHandleVerifier [0x006FA152+3079639]
	GetHandleVerifier [0x006FC4C9+3088718]
	GetHandleVerifier [0x005E4F0E+1944467]
	GetHandleVerifier [0x00700D26+3107243]
	GetHandleVerifier [0x005E4D7F+1944068]
	GetHandleVerifier [0x0057F306+1527691]
	GetHandleVerifier [0x005801A8+1531437]
	GetHandleVerifier [0x00589723+1569704]
	BaseThreadInitThunk [0x75143744+36]
	RtlSetCurrentTransaction [0x7782A064+212]
	RtlSetCurrentTransaction [0x7782A02F+159]

ERROR

======================================================================
ERROR: testFullRun (__main__.BattorWrapperDeviceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\b\build\slave\catapult\build\catapult\common/battor/battor/battor_wrapper_devicetest.py", line 54, in testFullRun
    battor.StartTracing()
  File "C:\b\build\slave\catapult\build\catapult\common/battor/battor\..\battor\battor_wrapper.py", line 120, in StartTracing
    self._SendBattorCommand(self._START_TRACING_CMD)
  File "C:\b\build\slave\catapult\build\catapult\common/battor/battor\..\battor\battor_wrapper.py", line 216, in _SendBattorCommand
    'Outputted: %s' % (cmd, status))
BattorError: BattOr did not complete command 'StartTracing' correctly.
Outputted: 

----------------------------------------------------------------------
Ran 1 test in 30.376s

FAILED (errors=1)
step returned non-zero exit code: 1
@@@STEP_FAILURE@@@

@anniesullie @aschulm @randalnephew

**Comment by nedn** [comment] 2016-05-06 21:54
This only happens on build79-b1. So I suspect this is a hardware failure... hmmm

@dave-2

**Comment by nedn** [comment] 2016-05-06 21:59
@randalnephew can you disable battor smoke test for now to unblock catapult CQ? YOu can look into https://code.google.com/p/chromium/codesearch#chromium/src/third_party/catapult/catapult_build/build_steps.py&l=19

**Comment by randalnephew** [comment] 2016-05-06 22:11
Definitely a HW failure. The BattOr is timing out.

[0506/145658:FATAL:battor_agent_bin.cc(87)] Fatal error when communicating with the BattOr: TIMEOUT

**Comment by aschulm** [comment] 2016-05-06 22:29
Excellent, I was hoping to hit a bug in the firmware (or it's it's
interface with software).Now for us to check out the logs and see what went
wrong. Charlie, any idea where to get that data?

**Comment by zeptonaut** [comment] 2016-05-09 16:05
@aschulm, when you say "logs", do you mean logs of the actual bytes sent over the wire? We don't have that right now, although it might be fairly trivial to add a flag to the BattOr agent that would allow the raw received / sent bytes to be written to a file (probably some temp file). It may be worth it to try to then keep those logs around in cloud storage for failed runs for a few days so that it allows us to debug the logs by hand. 

@nedn, do you have any idea how hard this might be?

Also, I suspect this is a problem with the agent not being resilient enough to inevitable hardware failures (like garbled bytes on the wire) rather than a problem with the hardware itself. Aaron and I saw something similar to this a while ago where, even though we were calling `Flush()` the serial connection before starting communication with the BattOr, there were still bytes from old connections stuck on the wire. I vaguely remember that we thought this might only be flushing the bytes that were buffered in software but not the bytes that were still on the wire. I think it's likely that this is the bug that we're hitting, and that we'll need to do something like manually pull all old bits from the wire in our own flush wrapper.

**Comment by nedn** [comment] 2016-05-09 16:10
@zeptonaut: if you can add the --log to battor_agent_bin.exe, that should be simple to do things like uploading to cloud storage or just printing out the whole log on stdout. 
Seems like the next step would be adding log/try the fix you mention & update the battor_agent_bin version in https://github.com/catapult-project/catapult/blob/master/common/battor/battor/battor_binary_dependencies.json?

Degrade this to P1 since this no longer blocks catapult CQ.

**Comment by aschulm** [comment] 2016-05-09 16:44
I will see if I can reproduce the problem locally. Following on to what @zeptonaut said, I think the problem is that the current battor_agent doesn't retry the init message several times if it doesn't receive an ACK. This will clear out any bytes that may be stuck on the wire. One thing that may be worth checking is to see if that BattOr that is attached to the CQ machine is blinking or not and what color.

**Comment by nedn** [comment] 2016-05-09 16:46
We can try reenabling the battor test in a CL & send out "git cl try", then go to the lab to see what's going there.
@randalnephew : want to do that this afternoon?

**Comment by randalnephew** [comment] 2016-05-09 19:01
Unfortunatly it is now passing:
https://build.chromium.org/p/tryserver.client.catapult/builders/Catapult%20Windows%20Tryserver/builds/2966

**Comment by nedn** [comment] 2016-05-09 19:19
Randy: can you do multiple "git cl try" run? If they keep passing, I think we can reenable the test & then have @zeptonaut to add more logging.

**Comment by zeptonaut** [comment] 2016-06-08 18:22
Update: weeks later, I now recognize the traceback as the result of https://bugs.chromium.org/p/chromium/issues/detail?id=603309, which I fixed weeks ago. However, I haven't been able to upload the fixed binary to cloud storage yet due to #2381.

Once the upload is successful, I anticipate this problem to be reduced, although there are probably still some bugs causing flakiness.

**Comment by zeptonaut** [comment] 2016-06-08 18:23
There's also a separate problem where, if the BattOr agent produces the trace data but then crashes, the associated benchmark succeeds rather than fails, which we probably don't want. That problem is being tracked at http://crbug.com/618141

**Comment by zeptonaut** [comment] 2016-07-08 16:55
Going to close this: we've fixed all problems related to this.

**Closed by zeptonaut** 2016-07-08 16:55 UTC
Labels: P1, Power-Infra
