### ISSUE TITLE
Recording trace in Chrome Canary with all default categories enabled shows no trace

### ISSUE THREAD

**Issue by zeptonaut** [catapult-project/catapult#2416] opened 2016-06-16 23:01 UTC
@natduca @petrcermak 

Seeing this on Chrome Canary Mac.

It appears that the trace events are still recorded, and that the hitboxing works (you can select events if you drag and they show up in the analysis pane). 

I don't have time to look into this now (preparing for the BattOr presentation at BlinkOn tomorrow morning), but I wanted to make sure that the bug got filed.

<img width="1395" alt="screen shot 2016-06-17 at 12 59 34 am" src="https://cloud.githubusercontent.com/assets/1407397/16135901/d7117e7e-3426-11e6-9ce1-f0675443ee3c.png">

**Comment by petrcermak** [comment] 2016-06-17 11:41
I'm unable to reproduce this on Chrome Canary Mac (_non_-Retina), 53.0.2770.0 (Official Build) canary (64-bit).

@zeptonaut: Could you please provide more details:

* How many tabs did you have open? URLs?
* How long was the recording?
* What do you mean by "all default categories"? "Web developer"? "Manually select settings" with all categories _not_ disabled by default?
* Did you use any special command-line flags?
* Did you do anything special: open a tab, close a tab, navigate, ...?
* Did you check if there was an error in DevTools (Cmd+Alt+J)?
* Can you reproduce this consistently? If not, what's the frequency?

**Comment by zeptonaut** [comment] 2016-06-17 12:12
This morning when I tried to reproduce it, I was unsuccessful, which is kind of scary.

I think that I had lots of tabs. The recording was 2-3s. By "all default categories", I selected "Manually select categories" and then selected all categories on the LHS and disabled all categories on the RHS. I believe that I opened a tab, navigated to YouTube, and either navigated back to my original tab or closed the tab before stopping the trace. I checked and the devtools console had some warnings (although nothing too scary), but no errors.

**Comment by zeptonaut** [comment] 2016-06-17 12:13
Also, I had the "system tracing" checkbox checked and a BattOr connected. However, when I tried to replicate it this morning with all of those settings, I was unsuccessful.

Maybe we should file this under "something to look out for" and just close the bug?

**Comment by petrcermak** [comment] 2016-06-17 14:08
Hm, still no luck reproducing the problem 😞

**Comment by nedn** [comment] 2016-06-21 03:45
When you are able to reproduce the problem, can you save the trace & show what does the json contains?

**Comment by zeptonaut** [comment] 2016-06-21 14:47
Will do.

On Mon, Jun 20, 2016 at 11:45 PM, Ned Nguyen <notifications@github.com>
wrote:

> When you are able to reproduce the problem, can you save the trace & show
> what does the json contains?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/catapult-project/catapult/issues/2416#issuecomment-227333331>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABV5pZRbiRMrF_SjHRa-tlocDnrC-j9Aks5qN15tgaJpZM4I35DU>
> .
>



-- 

Charlie Andrews |  Software Engineer |  charliea@google.com

**Comment by petrcermak** [comment] 2016-07-13 11:24
After further investigation, I have found that this is due to __maximum canvas size in Chrome__. That's why this issue happens mostly on Macs with Retina displays because Trace Viewer increases the size of the timeline track view canvas to get better-looking UI:

<tt>canvas.height _(number of virtual dots on the canvas)_ = canvas.style.height _(displayed size of the canvas)_ × window.devicePixelRatio _(physical pixels / device-independent pixels)_</tt>

The problem is that with large traces, the height of the timeline track view can be 16,384 pixels or more. On Retina displays (<tt>window.devicePixelRatio=2</tt>) this leads to canvas height exceeding 32,767, which is the [current limit for canvas dimensions in Chrome](https://bugs.chromium.org/p/skia/issues/detail?id=2122).

Screenshot demonstrating the problem ([source code](https://drive.google.com/file/d/0B8hP4MS3oRlpQk1SSVVnTlVodEE/view?usp=sharing)):
![screenshot from 2016-07-13 12 12 11](https://cloud.githubusercontent.com/assets/2546601/16801522/1016b334-48f3-11e6-86a7-9b989cebf829.png)

Unless the problem is fixed in Chrome, I can think of two _long-term_ solutions:

  1. Draw each track on a separate canvas. This has the nice benefit that tracks outside the current view could be skipped (faster horizontal scrolling, zooming, etc.). The downside is that the logic for drawing global events (especially flow events) would become a little more complex.
  2. Crop canvas to the visible area only (we already do this on the horizontal axis). In other words, simulate vertical scrolling by redrawing the canvas. I'm afraid that this would cause vertical scrolling to become too janky with dense traces.

The _short-term_ solution is to avoid increasing canvas size on high definition devices if it would cause the canvas size to become too large. The challenge there is that [quite a few files](https://cs.chromium.org/search/?q=file:src/third_party/catapult+devicePixelRatio+-file:test+file:track) would need to be modified to make this work.

@zeptonaut: What are your thoughts on this?

**Comment by nedn** [comment] 2016-07-13 15:18
"Draw each track on a separate canvas" seems like the right solution to me. For the short term fix, I think it's not too bad since one can just use sed to update that (window.devicePixelRatio || 1) code to some common function then edit that function to do the right thing?

**Comment by nedn** [comment] 2016-07-13 15:21
Actually, do most of the canvas drawing logic happens in https://cs.chromium.org/chromium/src/third_party/catapult/tracing/tracing/ui/base/draw_helpers.html ? If so, we can add size check there?

**Comment by petrcermak** [comment] 2016-07-13 15:25
That is only for the basic objects (e.g. slices). Many tracks do their own drawing: https://cs.chromium.org/search/?q=file:src/third_party/catapult+devicePixelRatio+-file:test+file:track. I think that the first step is to replace <tt>(window.devicePixelRatio || 1)</tt> with <tt>this.pixelRatio</tt> (new getter) in all tracks.

**Comment by zeptonaut** [comment] 2016-07-13 15:54
I definitely don't claim to be an expert on this, but my vote is for cropping the canvas to the visible area only. It seems like drawing flow events that span multiple canvases is going to be a nightmare.

**Comment by nedn** [comment] 2016-07-13 15:58
Oh, you're right that we have ui items that go across tracks. Can we draw the flow events using some short of overlay?

**Comment by zeptonaut** [comment] 2016-07-13 19:55
The problem I see with that is that the overlay couldn't be drawn using canvas: otherwise, it'd still run into the same problems if the track height got too big.

**Comment by petrcermak** [comment] 2016-07-14 09:53
@zeptonaut: That's not true. Canvas supports transparency ([source code](https://drive.google.com/open?id=0B8hP4MS3oRlpalpnV0N0dmFTQlE)):

![screenshot from 2016-07-14 10 42 16](https://cloud.githubusercontent.com/assets/2546601/16835281/e4c77142-49af-11e6-9358-d8d0d61a394c.png)

I'm worried that _cropping_ the canvas (and redrawing upon vertical scroll) will make the UI super-janky.

As for the global events spanning multiple tracks (if we did every track separately):

* It should be very straightforward to split __instant events__ given that they're straight vertical lines.
* As for the __flow events__, I'm not sure how difficult it would be to break up bezier curves, but we could just repeatedly draw the same curve on each visible track. Assuming that there aren't too many of these, the performance shouldn't suffer too much.

How about we make a _compromise_: Group __multiple tracks per canvas__. We could make it so that there are always at most 2 visible canvases. Hence, global events (e.g. flow events) would have to be drawn at most twice (in case we didn't have a good way to break them up). We'd still fix the main problem (blank timeline track view) and could improve performance in the future (by drawing the groups of tracks on demand).

**Comment by zeptonaut** [comment] 2016-07-14 13:56
IMO the ideal world is the one that we're in right now: everything is drawn on one big canvas, and it's easy to say "I want to point to this slice at <X, Y>", and everyone has the same understanding of X and Y. 

However, it sounds like our time in that world is limited for technical reasons. I think that you're probably right that rendering everything on one canvas and implementing scrolling ourselves is just asking for trouble. However, I'm worried that trying to keep track of what entities are on what canvas is going to get confusing, especially people that come in later after this decision was made and lack the historical context.

Not saying it's the wrong call, but I do think it'll be confusing.

**Comment by natduca** [comment] 2016-07-19 00:39
Maybe we should just collapse all the process tracks and if needed add an info bar to explain what we did. Could probably do it in the timeline_view.html model setter, for instance. That'll fix it mostly, and then people can complain about the bad ux...

The proper fix is unfortunately I think rewriting the timeline track view. I think there's a bug for that assigned to me, #1780

**Comment by randomascii** [comment] 2016-07-19 00:43
As an aside (also a hack that would temporarily address this problem I think), I wish that processes started out being collapsed because having them expanded by default makes the UI clunky when there are a lot of tabs. I think it would be easier to expand the couple of processes of interest rather than (as I do now) collapse the many processes that I'm not interested in.

And it sounds like a side effect of having processes collapsed by default would be that we would be much less likely to hit this 64 K pixel limit.

**Comment by petrcermak** [comment] 2016-07-19 10:26
This is not the first someone mentions they wish (some) tracks started collapsed.

Another option is to __crop__ the canvas if it would go over the limit and show an __info bar__ at the top saying something like _"Too many tracks to draw. Please collapse top tracks to see the ones at the bottom."_. This should actually be very easy to implement as the logic for track drawing wouldn't need to be modified at all. It's not ideal, but it's a first step. Thoughts?

**Comment by natduca** [comment] 2016-07-19 15:35
I'd be fine with that.

**Comment by zeptonaut** [comment] 2016-07-19 15:38
That also seems like a reasonable solution to me. It seems it makes sense to fix this problem with as little effort as possible given the relatively low # of users it actually affects at the moment.

**Comment by Apeliotes** [comment] 2016-08-08 23:53
Do any of you have time to pick this up?

**Comment by zeptonaut** [comment] 2016-08-09 13:21
I don't think I do right now :-/

**Comment by petrcermak** [comment] 2016-08-09 13:21
I'd really love to, but I'm swamped with perf alerts and bisects :disappointed:

**Comment by natduca** [comment] 2016-11-29 17:55
@Apeliotes kari, what if we built a simple quick feature into timeline_track_view that, after it initializes the canvas size the first time, it checks the dimension, and raises an "canvas-over-size" event. Then, the timeline_view can listen to that, and if it gets it, it can go through the various process tracks and sort them by number-of-threads, and tell the smallest ones to repeatedly collapse until we're <32k in height?

**Comment by zeptonaut** [comment] 2016-11-29 20:25
Is there any way that we could just take the extremely easy way out and just create an import error if the track size is too big? I have a feeling that most people would have no problem just rerecording the trace if it's too big, and for everyone else, it would be strictly better than the current solution, which is to just die without mention of why.

**Comment by natduca** [comment] 2016-11-29 20:29
The problem is, this isn't about the duration of the trace, its about how many tabs you have open on your computer. So we'd effectively be info-baring them and saying "please close some tabs". I think thats an option, just not very intuitive.... dunno, wdyt?

**Comment by zeptonaut** [comment] 2016-11-29 21:13
I agree it's not terribly intuitive, but I'm not sure if it's worth putting much effort into fixing it given how rarely this bug crops up. I don't think it's a whole lot more intuitive if we allow the trace the user to open the trace but then die or give a similar error after they open a few more tracks.

My feeling is that, if we just throw up an error saying "Ack! Your trace would take up too much vertical space, which is limited in the current implementation of trace viewer. Try rerecording the trace in a way that uses less vertical space."

I'd prefer to just say "close tabs" in the context of Chrome, but that would require a little more work: some Chrome-specific piece of code would have to rewrite the import error specifically for Chrome I think.

**Comment by Apeliotes** [comment] 2016-11-30 23:04
Did some digging. I don't think that collapsing the smallest tracks is the right thing to do. It ends up with odd behavior if you're interested in any of the collapsed tracks. (Like either getting the original error if you don't know to collapse other tracks first, or not being able to open one of the collapsed rows.) I agree that we probably want to do something about the offscreen content, or all of the content.

Cropping the canvas (if it doesn't lead to jank like Petr was worried about) or collapsing offscreen or all tracks would be better.

If we do collapse tracks, we may want to also warn people when they record such a trace since there will probably still be some oddness. (For example: tracks you're interested in collapsing on you when you scroll, or not being able to uncollapse rows.)

**Comment by natduca** [comment] 2016-11-30 23:12
I'm happy with anything as long as we do something :D... even infobaring "close some tabs" would be progress 🗡

**Comment by Apeliotes** [comment] 2016-12-01 18:19
I think there are too many questions on which long-term solution will work, and don't want to cause the weird UI corner cases of collapsing tracks. I'm moving forward with Petr's suggested short-term fix of not increasing canvas size on high definition devices if it would cause the canvas size to become too large. This should drastically reduce the occurrences of this bug until we figure out the correct long-term solution with the cost of a little definition. Should have a cl up later today.

**Comment by jreck** [comment] 2017-01-04 19:26
I believe this is fixed now as of https://github.com/catapult-project/catapult/commit/78b00b99cf86f25ff0082ae9a7b0799b1447a56f

**Closed by jreck** 2017-01-04 19:26 UTC
Labels: Bug, P1, Trace Viewing
