### ISSUE TITLE
Perf dashboard not displaying Android ref build values.

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#2046] opened 2016-02-22 19:17 UTC
As of last Friday, we enabled ref builds on Android, but the dashboard does not seems to be picking them up.

Example: https://build.chromium.org/p/chromium.perf/builders/Android%20Galaxy%20S5%20Perf%20%283%29/builds/1408 

If you click on the Results Dashboard link on any of the tests that has a ".reference" suffix, it does not show a ref graph beside the test graph.

@Apeliotes @nedn

**Comment by anniesullie** [comment] 2016-02-22 19:19
@chrisphn

**Comment by chrisphn** [comment] 2016-02-22 22:09
Points were added.  https://chromeperf.appspot.com/report?sid=4859c0adca2bfc35b79d151be15614845f269594d33d3a23e2d7da9bf6d7b442&rev=376729

The dashboard link is just missing a test name.  Sent a change to automatically select a test.
This will also make it easier to browse added tests: https://github.com/catapult-project/catapult/issues/2048

**Comment by qyearsley** [comment] 2016-02-22 22:25
I don't think it's just that the dashboard link is missing a test name; the test suite name in the dashboard link is also incorrect (it shouldn't contain ".reference"). The chartjson that is sent is also incorrect; it contains "is_ref": false.

I believe this an issue on the sender side (runtest.py or results_dashboard.py).

**Comment by chrisphn** [comment] 2016-02-22 22:29
Right, "is_ref" is false.  Not sure if it's intentional,  but the data is uploaded under for example:

ChromiumPerf/android-galaxy-s5/media.mse_cases.reference / append / AV_buffer_post_load

**Comment by qyearsley** [comment] 2016-02-22 22:35
runtest.py decides whether or not the data is reference build data based on whether or not the first part of the test command ends with `run_benchmark` and the args to the command include `--browser=reference`; I think it might be breaking because the first part of the command is /usr/bin/python instead of .../run_benchmark.

https://chromium.googlesource.com/chromium/tools/build/+/master/scripts/slave/runtest.py#1567

**Comment by qyearsley** [comment] 2016-02-23 22:49
Note, this should be fixed by @dave-2 's CL https://codereview.chromium.org/1718373002

**Comment by fmeawad** [comment] 2016-02-24 19:05
It is now appearing as a new test suite: https://chromeperf.appspot.com/report?sid=48b3609a8553352c28371507a7f29d868e87672df5da740b8a93f2fd12178f65 and not ref on the main test suite

**Comment by dave-2** [comment] 2016-02-26 01:10
I'm looking more closely into it. I think we've misinterpreted how it works -- runtest.py isn't involved in running the tests at all.

**Comment by dave-2** [comment] 2016-02-26 04:53
Nope, I'm technically correct, but overall wrong. Looks like `runtest.py` is used for reporting the results, so it is still involved.

**Comment by dave-2** [comment] 2016-02-29 18:57
Landed a [CL](https://codereview.chromium.org/1718373002) for `is_ref`. But the graphs still don't look quite right. Is there anything else we need to do?

**Comment by anniesullie** [comment] 2016-03-01 04:42
Looks like somehow the '.reference' gets dropped from the test suite name on the desktop recipe.

Example android ref build (check test_suite_name):
https://uberchromegw.corp.google.com/i/chromium.perf/builders/Android%20Galaxy%20S5%20Perf%20(3)/builds/1466/steps/media.mse_cases.reference/logs/json.output

Example desktop:
https://uberchromegw.corp.google.com/i/chromium.perf/builders/Win%207%20x64%20Perf%20%282%29/builds/6461/steps/media.mse_cases.reference/logs/json.output

Android ref graphs end up here:
https://chromeperf.appspot.com/report?sid=1b8e967eb1beb50a457ad833b909603b0aafb3a1600a97327fb98b8038a7b5be

**Comment by qyearsley** [comment] 2016-03-03 00:30
Note, this technically isn't a dashboard bug, but it's a bug in whatever mechanism is responsible for coming up with test_suite_name in that JSON.

**Comment by qyearsley** [comment] 2016-03-03 00:53
Notes: Looks like test_suite_name is determined by the --test-type argument passed to runtest.py, which includes .reference in case of the android perf bots, but not in the non-android perf bots.

This is likely due to the fact that android perf bots use the android/perf recipe while the others use the chromium recipe.

**Comment by anniesullie** [comment] 2016-03-03 19:43
I'm not sure if anyone is familiar enough with the android recipe to fix it there :(
@randalnephew @jbudorick would you be able to help?

If not, how horrible would it be to workaround in `results_dashboard. MakeDashboardJsonV1` by always stripping ".reference" from `test_suite_name`?

**Comment by anniesullie** [comment] 2016-03-03 19:56
I implemented a workaround in https://codereview.chromium.org/1765593002, if anyone can fix the root cause instead please weigh in!

**Comment by randalnephew** [comment] 2016-03-03 20:00
Me and John are at the convergence until the end of the week, so we will probably not get a chance to look at this for a little while.

I am out all next week as well. I will try to take a look when I get back if no one else has.

**Comment by qyearsley** [comment] 2016-03-03 20:11
I may have time to look at this next week :-)

**Comment by anniesullie** [comment] 2016-03-03 21:36
Workaround is submitted, but this should still get a proper recipe fix, so leaving open.

**Comment by anniesullie** [comment] 2016-03-04 16:35
After the workaround, we are seeing data: https://chromeperf.appspot.com/report?sid=8059eb78c798a7e049c6a859cd52441da23d44739c7914479288c479622752af&rev=379269

I am going to start kicking off migrations for the bad data with ".reference" in the test suite name. I'm starting with kraken.reference.

**Comment by anniesullie** [comment] 2016-03-04 16:45
I just noticed this is an issue for the internal waterfall as well (but hooray for having ref builds on internal!)

@Apeliotes did you add the ref builds to internal waterfall? If you are able to take a look, please do, otherwise maybe @randalnephew or @jbudorick could look next week?

**Comment by anniesullie** [comment] 2016-03-08 14:55
@perezju since you are making recipe changes in clank right now, would you mind doing something similar to https://codereview.chromium.org/1765593002 for the ref builds (making it so the perf dashboard upload doesn't have '.reference' in the test_suite_name field)?

**Comment by perezju** [comment] 2016-03-08 15:08
I think internal bots should eventually pick up the same change in https://codereview.chromium.org/1765593002 and apply the same transformation. Anyway, maybe file an internal bug with details of the bots with ref builds and I can take it from there.

**Comment by anniesullie** [comment] 2016-03-08 16:21
Thanks, @perezju! I started filing a bug, looking at the chartjson output by the recent builds, and it looks like the bots did already pick up the change. So not filing a bug for now!

**Comment by anniesullie** [comment] 2016-05-05 13:41
I deleted all the broken "testname.reference" data. This is now **fixed**.

**Closed by anniesullie** 2016-05-05 13:41 UTC
Labels: Bug, Perf Dashboard
