### ISSUE TITLE
Add links to memory-infra benchmarks doc to memory regressions

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#3128] opened 2017-01-09 18:00 UTC
@perezju has landed the first version of our memory-benchmark docs:
https://chromium.googlesource.com/chromium/src/+/master/docs/memory-infra/memory_benchmarks.md

It would be great if this somehow was attached to bugs with memory regressions, something like:
See here for doc about memory benchmarks and how to repro them.

**Comment by primiano** [comment] 2017-01-09 18:01
@anniesullie can you triage this? (not hi prio)

**Comment by anniesullie** [comment] 2017-01-12 13:14
@eakuefner @benshayden @jessimb This is a super useful sheriffing feature. We already pipe some documentation from benchmark comments through to the test description, and it would be really cool to pipe a "what to do if you regressed this benchmark" link through as well.

@dave-2 @simonhatch This is an example of where we'd use the data pipe in pinpoint (or probably short-term we could do this in dashboard since Simon moved the output generation to dashboard). It'd be really cool to have the bisect look up the test in question and spit the link out in the bug.

**Comment by simonhatch** [comment] 2017-01-12 15:22
Sure easy enough, which tests, system_health/memory.*?

**Comment by anniesullie** [comment] 2017-01-12 15:26
Short term we can do it by test name. Long term the `TestMetadata` entity in the datastore should store the link.

@primiano @perezju what are the test suites we should add this documentation to?

**Comment by perezju** [comment] 2017-01-12 15:37
Let's add the link for both:

* `system_health.memory_*`
* `memory.top_10_mobile*`

In it's current form the page might be a bit confusing for people landing there because of a `memory.top_10_mobile` regression, but I can add a new small section detailing the few differences and particularities of that benchmark.

**Comment by eakuefner** [comment] 2017-01-23 23:45
@simonhatch looks like this is probably fixed for now, right?

**Comment by simonhatch** [comment] 2017-01-23 23:48
I assumed we were keeping it open for the long-term solution of storing this kind of data in TestMetadata.

**Comment by eakuefner** [comment] 2017-01-23 23:49
Sounds good, I can add this to the histogram pipeline blocker tree I'm building.

**Comment by simonhatch** [comment] 2017-09-21 18:50
There's a more recent, general request for doc urls for benchmarks in #3690 so let's just close this and keep the other open.

**Closed by simonhatch** 2017-09-21 18:50 UTC
Labels: Hotlist:Histogram Pipeline, Infrastructure, Perf Dashboard
