### ISSUE TITLE
Spacing track visual glitch

### ISSUE THREAD

**Issue by petrcermak** [catapult-project/catapult#2100] opened 2016-03-07 17:58 UTC
There are __gaps__ in the heading (on the left):

![screenshot from 2016-03-07 17 56 19](https://cloud.githubusercontent.com/assets/2546601/13578127/f6b0cf7a-e48d-11e5-8b5a-4629f2c291cb.png)

This was most likely caused by 64ae144a61f13e89486f65a15033c130c1342ca3, so I'm assigning this to @zeptonaut.

**Comment by petrcermak** [comment] 2016-03-07 17:59
@zeptonaut: Please revert https://codereview.chromium.org/1764673002

**Comment by zeptonaut** [comment] 2016-03-08 14:22
Are we sure this is a bug / is caused by the patch that I submitted? I'm synced to head right now, and the tracks on the left still have gaps:

![unnamed image 1](https://cloud.githubusercontent.com/assets/1407397/13604095/2baeb33c-e50f-11e5-95b0-55129c430d5b.png)

I made sure to restart my dev server as well, just in case some state was stuck.

**Comment by zeptonaut** [comment] 2016-03-08 14:46
Sigh, I'm an idiot. While I was investigating the cause, I reverted the revert, and accidentally had that patched in at head. Closing this again.

**Closed by zeptonaut** 2016-03-08 14:46 UTC
Labels: Bug, Good First Bug, Trace Viewing
