### ISSUE TITLE
--no-first-run is intermittently ignored on Android with browser_test_runner

### ISSUE THREAD

**Issue by kenrussell** [catapult-project/catapult#3122] opened 2017-01-06 05:13 UTC
Though telemetry/telemetry/internal/backends/chrome/chrome_browser_backend.py specifes --no-first-run, occasionally, the browser brings up the sign-in page.

This was seen while developing https://codereview.chromium.org/2611263002 , testing on an unlocked Nexus 5X with stable Chrome.

I found that specifying --no-first-run manually, at the application level, (by calling SeriallyExecutedBrowserTestCase.SetBrowserOptions), seemed to work around the problem for some reason. However, without it, the test log clearly shows that it's being specified each time the browser is launched. See the attached log from this run:

./content/test/gpu/run_gpu_integration_test.py gpu_process --browser=android-system-chrome -v > output.txt 2>&1

At the time the log was gathered, the on-device browser was displaying the Chrome sign-in page. It only recovered by timing out.

Is there a problem with this test harness and potentially rapid restarting of the browser?

[hung-browser.txt](https://github.com/catapult-project/catapult/files/689025/hung-browser.txt)

**Comment by kenrussell** [comment] 2017-01-10 21:34
CC'ing @nedn @ehanley324 .

This was reproducible locally, but presumably not on the bots.

**Comment by kenrussell** [comment] 2017-01-18 00:55
CC'ing @jbudorick @zhenyao .

We are running into this frequently when trying to run the WebGL 2.0 conformance tests locally against a Google Pixel phone.

We noticed the following error:
<pre>
(WARNING) 2017-01-17 16:52:03,433 gpu_integration_test._RestartBrowser:47  Restarting browser due to unexpected test failure
(WARNING) 2017-01-17 16:52:03,768 gpu_integration_test.StartBrowser:29  Starting browser, attempt 1 of 3
(WARNING) 2017-01-17 16:52:05,766 flag_changer.__init__:42  cmdline_file argument of <class 'devil.android.flag_changer.FlagChanger'>() should be a file name only (not a full path).
(WARNING) 2017-01-17 16:52:05,766 flag_changer.__init__:46  Client supplied '/data/local/chrome-command-line', but '/data/local/tmp/chrome-command-line' will be used instead.
</pre>

Is it possible there's a bug in this code where the command-line arguments it's passing are silently dropped?

**Comment by nedn** [comment] 2017-01-18 01:05
Probably due to @perezju 's work to change the command-line flag on Android.

**Comment by kenrussell** [comment] 2017-01-18 01:34
Thanks @nedn . Could you find an owner for this bug? To reproduce, just install Chrome Canary on a Google Pixel, plug it in, and run:

<pre>
./content/test/gpu/run_gpu_integration_test.py webgl_conformance --browser=android-chrome-canary --webgl-conformance-version=2.0.0
</pre>

After a few tests, one will fail, and the harness will tear down the browser and attempt to bring it back up. The bringup usually displays Chrome's sign-in screen, breaking the test execution flow.

Also CC'ing @kainino0x.

**Comment by perezju** [comment] 2017-01-18 10:03
I'll look into this. Does it also reproduce on other devices? Which Android version is there on the phone?

**Comment by perezju** [comment] 2017-01-18 11:04
The `hung_browser.txt` log seems to be from before my changes were introduced (it still uses `android_command_line_backend` rather than `flag_changer`).

Setting up a phone now to see if I can reproduce locally.

**Comment by kenrussell** [comment] 2017-01-18 19:13
I've seen this both on a Nexus 5X running:
bullhead-userdebug 6.0.1 MTC19V 2862947 dev-keys

as well as a Google Pixel running:
marlin-userdebug 7.1 NME60B 3231051 dev-keys

**Comment by perezju** [comment] 2017-01-27 00:09
Some updates, I sat together with zmo@ today and we were able to reproduce the issue on a Pixel, but strangely not on my N5.

I confirmed that the command line is set up correctly, flag_changer reads back the cmd_line file from the device after writing it and it correctly reports finding the flags:

`'--disable-fre', '--no-default-browser-check', '--metrics-recording-only', '--ignore-certificate-errors', '--disable-default-apps', '--test-type=gpu', '--disable-external-intent-requests', '--disable-domain-blocking-for-3d-apis', '--proxy-server=socks://localhost:44875', '--disable-component-extensions-with-background-pages', '--disable-gesture-requirement-for-media-playback', '--enable-gpu-benchmarking', '--enable-net-benchmarking', '--enable-remote-debugging', '--disable-gpu-process-crash-limit', '--enable-experimental-canvas-features', '--js-flags=--expose-gc', '--enable-es3-apis', '--disable-gpu-watchdog', '--no-first-run', '--disable-background-networking'`

I checked whether this was a timing issue (if we were removing the flags before Chrome had a chance to read them), but this is apparently not the problem. Adding delays after writing the file and before removing it did not solve the issue.

From the Chrome side, I grabbed a [logcat](https://github.com/catapult-project/catapult/files/733951/adb_logcat.txt), and we do also see, correctly:

```
01-26 14:55:36.282 17938 17938 I cr_CommandLineInitUtil: Using alternative command line file in /data/local/tmp/chrome-command-line
```

Full [Telemetry log](https://github.com/catapult-project/catapult/files/733953/output_with_v3.txt) until the command hanged also available.

@nedn @primiano any ideas of what could be going on?

while I get back to work on this (probably next week), @kenrussell could it be possible to log from within Chrome the contents of the command line read, and see whether the proper flags show up there?

**Comment by kenrussell** [comment] 2017-01-27 00:22
@perezju yes, @zhenyao and I can help with logging the actual command line read by Chrome.

**Comment by primiano** [comment] 2017-01-27 01:36
@perezju there are two ways you can check if the command line actually makes it to chrome:
1) look at chrome://version/
2) if you grab a trace, the trace metadata has the cmdline (click the "M"  button in chrome://tracing after having loaded the trace)

**Comment by perezju** [comment] 2017-02-14 12:00
@zhenyao is this issue still affecting you? I did give it a try on a Nexus 6P (sadly Pixels are scarce!) but still unable to repro.

**Comment by kenrussell** [comment] 2017-04-28 23:10
Note: possible reoccurrence of this in http://crbug.com/716564 . May be the case that command lines are not being propagated to Chrome on this non-rooted device.

**Comment by perezju** [comment] 2017-05-02 10:28
Is there a way to query via devtools the flags that were used to launch Chrome? This way we could query those from Telemetry to ensure that flags were correctly received.

**Comment by primiano** [comment] 2017-05-02 10:33
@perezju I don't think there is a devtools api to check the cmdline flags. However the trace metadata contains the cmdline. Is that enough or is it too late (trace gets collected only at the end)

**Comment by perezju** [comment] 2018-03-08 16:31
From http://crbug.com/716564 sounds like the issue of getting the command line from Chrome has also been fixed. Closing this. Feel free to reopen if the issue reoccurs.

**Closed by perezju** 2018-03-08 16:31 UTC
