### ISSUE TITLE
Broken view of trace that includes telemetry & chrome events

### ISSUE THREAD

**Issue by nedn** [catapult-project/catapult#2759] opened 2016-09-02 16:39 UTC
[http___www_nick_com_games0.html.zip](https://github.com/catapult-project/catapult/files/452519/http___www_nick_com_games0.html.zip)

Another way to reproduce this is patch https://codereview.chromium.org/2301523007/ & run:
`./tools/perf/run_benchmark --browser=default page_cycler_v2.typical_25 --story-filter=nick --pageset-repeat=1 --output-format=json --browser=android-chrome-beta`

I suspect this is a bug in clock sync.

**Comment by zeptonaut** [comment] 2016-09-02 19:26
(Duplicate of #2600)

**Closed by zeptonaut** 2016-09-02 19:26 UTC
Labels: Trace Model, Trace Viewing
