### ISSUE TITLE
[📍] Link to the builder during building

### ISSUE THREAD

**Issue by fmeawad** [catapult-project/catapult#4170] opened 2018-01-18 20:04 UTC
https://pinpoint-dot-chromeperf.appspot.com/job/16d1ee20840000

It seems that there is a build failure, but I am not sure how to get to the builder and investigate the failure.

**Comment by dave-2** [comment] 2018-01-19 05:06
Duplicate of #3899

**Closed by dave-2** 2018-01-19 05:06 UTC
Labels: Bisect
