### ISSUE TITLE
Data stoppage alerts only show up after triaging previous alerts

### ISSUE THREAD

**Issue by CalebRouleau** [catapult-project/catapult#3111] opened 2017-01-04 00:42 UTC
I triaged all of the alerts on

https://chromeperf.appspot.com/alerts?sortby=end_revision&sortdirection=down&sheriff=Chromium%20Perf%20AV%20Sheriff

and then new alerts from 2016-12-07 and 2016-12-16 appeared. 

I think they should have showed up before but instead all I saw were the older alerts.

**Comment by chcunningham** [comment] 2017-01-04 00:51
Before triage:
![image](https://cloud.githubusercontent.com/assets/12039355/21628422/430b876e-d1d4-11e6-9efc-2e4c752086a6.png)

After triage:
![image](https://cloud.githubusercontent.com/assets/12039355/21628494/c50aeffc-d1d4-11e6-9285-d6c1a0d5823e.png)

**Comment by CalebRouleau** [comment] 2017-01-04 01:59
This is reliably reproducible. I have triaged two more sets of alerts only to have more alerts pop up again.

**Comment by CalebRouleau** [comment] 2017-01-04 02:01
![triage](https://cloud.githubusercontent.com/assets/1326100/21629580/9dad4efa-d1de-11e6-9e19-ac599940af8f.png)

**Comment by CalebRouleau** [comment] 2017-01-04 02:02
![triage2](https://cloud.githubusercontent.com/assets/1326100/21629602/c1c84b32-d1de-11e6-8250-784b74f5417c.png)

**Comment by CalebRouleau** [comment] 2017-01-04 02:05
@anniesullie for assigning to owner.

**Comment by anniesullie** [comment] 2017-01-04 12:52
We limit it to 50 at once because it takes a long time to load them.

**Comment by chcunningham** [comment] 2017-01-04 16:35
Understood. IMO it would be more clear if the UI said "50 / X alerts", and with a link to "load more".

**Comment by eakuefner** [comment] 2017-01-04 22:35
@jessimb

**Comment by anniesullie** [comment] 2017-01-05 17:55
@jessimb: the performance problem here is really similar to the one you avoided in your CL to add test units. If you look at the [alerts page](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/alerts.py#L176) code it checks the stoppage alert `last_row_date`, which is a [computed property on `StoppageAlert`](https://github.com/catapult-project/catapult/blob/master/dashboard/dashboard/models/stoppage_alert.py#L63).

To fix this, we'd need to:
1. Add a non-computed `last_row_date` property to `StoppageAlert`. (You'll need to name it something different of course).
2. Add code to set the property when stoppage alerts are created.
3. Run a job to set the new property for all untriaged data stoppage alerts. You may want to try running a task queue job instead of a mapreduce since they seem more reliable.
4. Switch usages to the new property.

After that, you can increase the limit on stoppage alerts.

**Comment by anniesullie** [comment] 2017-01-06 04:31
Part 2 CL up for review: https://codereview.chromium.org/2616793004

**Comment by jessimb** [comment] 2017-02-01 23:46
This is fixed now.

**Closed by jessimb** 2017-02-01 23:46 UTC

**Comment by CalebRouleau** [comment] 2017-02-01 23:57
What is the new limit on stoppage alerts?

**Comment by jessimb** [comment] 2017-02-01 23:58
It will fetch up to 5000 and display up to 500. That goes for regressions and stoppage alerts.
