### ISSUE TITLE
Perf issues are not updated with bisect results due to exception in update_bug_with_results.

### ISSUE THREAD

**Issue by vuppalapu** [catapult-project/catapult#2295] opened 2016-04-29 17:37 UTC
I think this related to new formatting of bisect results https://codereview.chromium.org/1920543002/

Caught Exception ValueError: math domain error (/base/data/home/apps/s~chromeperf/dev-sullivan-69a681ae.392415948149617343/dashboard/update_bug_with_results.py:79)
Traceback (most recent call last):
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-69a681ae.392415948149617343/dashboard/update_bug_with_results.py", line 76, in get
    _CheckJob(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-69a681ae.392415948149617343/dashboard/update_bug_with_results.py", line 110, in _CheckJob
    _CheckBisectJob(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-69a681ae.392415948149617343/dashboard/update_bug_with_results.py", line 124, in _CheckBisectJob
    _PostResult(job, issue_tracker)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-69a681ae.392415948149617343/dashboard/update_bug_with_results.py", line 169, in _PostResult
    comment = bisect_report.GetReport(job)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-69a681ae.392415948149617343/dashboard/bisect_report.py", line 96, in GetReport
    result += _RevisionTable(results_data)
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-69a681ae.392415948149617343/dashboard/bisect_report.py", line 129, in _RevisionTable
    revision_rows = [RevisionRow(r) for r in results_data['revision_data']]
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-69a681ae.392415948149617343/dashboard/bisect_report.py", line 123, in RevisionRow
    _FormatNumber(r['std_dev']),
  File "/base/data/home/apps/s~chromeperf/dev-sullivan-69a681ae.392415948149617343/dashboard/bisect_report.py", line 154, in _FormatNumber
    return str(round(x, 5-int(math.floor(math.log10(abs(x))))))
ValueError: math domain error

**Comment by anniesullie** [comment] 2016-04-29 18:35
Isn't this a dupe of #2293?

**Comment by anniesullie** [comment] 2016-04-29 18:55
Closing as dupe

**Closed by anniesullie** 2016-04-29 18:55 UTC
Labels: Bisect, Perf Dashboard
