### ISSUE TITLE
Perf Dashboard: WebRTC alerts page not loading when logged in when chromium account.

### ISSUE THREAD

**Issue by ivocreusen** [catapult-project/catapult#2150] opened 2016-03-18 10:03 UTC
Chrome version: 49.0.2623.87 (Linux)
URL: https://chromeperf.appspot.com/alerts?sheriff=WebRTC%20Perf%20Sheriff&sortby=test&sortdirection=down&improvements=true

Javascript warnings:

'Object.observe' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/6147094632988672 for more details.
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
core-overlay.html:348 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

Please describe the problem:

I am not able to use the WebRTC performance dashboard using my ivoc@chromium.org account. I am signed in to both the browser and the page (by clicking on "sign in" on the upper right). The page gets stuck on the rolling wheel animation, and never gets past this. Earlier this week it was working fine for me, and other people have no problems with the page right now. I have tried chrome M49 and M50, I've tried wiping cookies, I've tried restarting chrome and restarting my machine, and none of these made any difference. I can see the page using my @google.com account, but I'm not able to triage using that account.

**Comment by qyearsley** [comment] 2016-03-18 16:28
Given that you tried multiple times, including after wiping cookies, and with different versions of Chrome, and the page was stuck on the rolling wheel animation, it definitely sounds like this was a problem with the dashboard.

Although, I'm not able to reproduce it currently -- @chrisphn or @anniesullie can you reproduce it by going to https://chromeperf.appspot.com/alerts?sheriff=WebRTC%20Perf%20Sheriff&sortby=test&sortdirection=down&improvements=true ?

Searching for errors in requests to /alerts, I found two curious recent entries in the logs, but they both look irrelevant:

```
03:28:06.681 POST 500 225 B 5.11 s Chrome 51 /alerts
  File ".../dashboard/alerts.py", line 44, in post
    if not _SheriffIsFound(sheriff_key):
  File ".../dashboard/alerts.py", line 70, in _SheriffIsFound
    sheriff_entity = sheriff_key.get()
HTTPException
```

```
02:49:14.980 GET 404 0 B 2 ms Chrome 47 /dashboard/elements/Alerts-page.html
Static file referenced by handler not found: dashboard/elements/Alerts-page.html
```
The JS warnings there are not relevant - those show up on every page as long as we're still using Polymer 0.5.

**Comment by anniesullie** [comment] 2016-03-18 16:40
Thanks for the detailed report, Ivo!

The root problem is that ivoc@chromium.org is not a member of the external/project-chromium-committers group on chrome-infra-auth. Can you file a bug on crbug.com with label Infra asking to be added?

I also see the infinite spinner when looking at the page when logged out. I'll file a bug to get that fixed.

**Comment by anniesullie** [comment] 2016-03-18 16:46
Filed #2153 about the spinner being confusing. Closing this issue since Ivo will need to file a separate ticket to get added to the proper group.

**Closed by anniesullie** 2016-03-18 16:46 UTC
Labels: Bug, Perf Dashboard
