### ISSUE TITLE
Graphs Page: Alerts aren't checked when triaged from alerts page.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#2647] opened 2016-08-10 16:53 UTC
Click on alert from alerts page, graph, not checked when you reach graph page.

**Comment by anniesullie** [comment] 2016-08-11 13:51
I'm closing this as a dupe of #2655 since that one has screenshots in case anyone is confused by the description.

**Closed by anniesullie** 2016-08-11 13:51 UTC
Labels: Perf Dashboard, Polymer 1.0 Migration
