### ISSUE TITLE
Trace viewer displays no trace events

### ISSUE THREAD

**Issue by rschoen** [catapult-project/catapult#3030] opened 2016-11-23 18:30 UTC
Investigating crbug.com/667391, in comment 10 the reporter posted a trace but when I open it I get lots of threads and no trace events. Attached the trace and a screenshot of what I see.

Trace was taken on Mac with Chrome 55.0.2883.52, I'm trying to open on a Chromebook with 55.0.2883.54.

![screenshot 2016-11-23 at 10 27 21 am](https://cloud.githubusercontent.com/assets/3644011/20574078/b249c4ca-b167-11e6-993a-a508b39179e4.png)

[trace_.tmp.printPreviewInfiniteLoop.json.gz](https://github.com/catapult-project/catapult/files/609699/trace_.tmp.printPreviewInfiniteLoop.json.gz)

**Comment by zeptonaut** [comment] 2016-11-23 20:16
I have an unconfirmed hunch that this is related to the performance regression that we've seen lately in importing. I gunzipped the trace and put it in the tracing/test_data directory at HEAD and was able to open it once with the data being displayed out of 15 or so attempts: on the others, either the tab crashed, the page loaded and was blank, or the page never loaded. This flakiness makes me think that it might be due to some strange behavior exhibited when trace viewer is pushing the bounds of a tab's memory limits: memory that was allocated during the slower import that we've seen lately.

The HTMLified trace is only 150MB, and the JSON is only 90MB, so this would indeed be a pretty big regression. I think that we used to be able to handle more like 200MB traces.

I'm going to see if I can determine how much memory is being used to import this trace.

FYI @eakuefner @benshayden @Apeliotes @nedn that this is happening.

**Comment by benshayden** [comment] 2016-11-23 20:36
This looks like https://github.com/catapult-project/catapult/issues/563

**Comment by zeptonaut** [comment] 2016-11-23 20:44
+lots to @benshayden's comment. This is by far the most likely explanation. @rschoen, can you ask for the trace to be rerecorded without so many tabs open?

**Comment by rschoen** [comment] 2016-11-23 20:46
Done, will report back.

**Comment by nedn** [comment] 2016-11-23 20:47
I remember the time's solution is to collapse all the threads by default when their count is high.

**Comment by eakuefner** [comment] 2016-11-28 21:50
@rschoen any report on the re-record? Should we remove the P0 label?

**Comment by rschoen** [comment] 2016-11-28 21:53
The reporter hasn't given another trace yet. I'm fine with this not being a P0.

**Comment by zeptonaut** [comment] 2016-12-01 21:20
Closing this as a duplicate of #2416

**Closed by zeptonaut** 2016-12-01 21:20 UTC
Labels: Bug, Trace Viewing

**Comment by Apeliotes** [comment] 2016-12-02 00:56
Ryan: try opening the trace on a non-high-res device.

**Comment by rschoen** [comment] 2016-12-02 18:04
Yep, that worked as a workaround. Thanks!
