### ISSUE TITLE
Graphs Page: Can't file new bugs.

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#2565] opened 2016-07-27 16:36 UTC
Always get "Error creating bug!". Not sure if this is valid since this is a non-default version.

**Comment by Apeliotes** [comment] 2016-07-27 22:53
I couldn't repro, and successfully filed a bug from this graph:

https://dev-aiolos-1c4bc232-dot-chromeperf.appspot.com/report?sid=35b05fcd47addf37fa6029bdeed3090ed018156dc2d892f371e06a38f7132301&rev=407961

I think this may have had the same root cause as https://github.com/catapult-project/catapult/issues/2566, which has been fixed in the above demo.

Simon: 
Can you repro on https://dev-aiolos-1c4bc232-dot-chromeperf.appspot.com ?

If yes:
1) Were you logged in?
2) Is that the same graphs page

**Comment by simonhatch** [comment] 2016-07-27 23:20
Yep, logged in with my chromium account. Just tried again on https://dev-aiolos-1c4bc232-dot-chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICghomPogoM and got an error creating bug.

**Comment by Apeliotes** [comment] 2016-07-28 19:23
I still can't repro. Sending this to Simon.

**Comment by simonhatch** [comment] 2016-07-28 19:31
<img width="1360" alt="screen shot 2016-07-28 at 3 29 41 pm" src="https://cloud.githubusercontent.com/assets/11619067/17226612/49cdc6d0-54d8-11e6-8d35-b1d557213f1c.png">

Screenshot, in case I'm doing something really stupid, like not logging in.

**Comment by anniesullie** [comment] 2016-07-29 13:59
@Apeliotes did you report the 401 errors to monorail team? I think that is the most we can do here.

**Comment by anniesullie** [comment] 2016-08-01 21:31
I'm going to close this since I think it's unrelated to the migration

**Closed by anniesullie** 2016-08-01 21:31 UTC
Labels: P1, Perf Dashboard, Polymer 1.0 Migration
