### ISSUE TITLE
Pinpoint - Investigate perf try job revisions

### ISSUE THREAD

**Issue by simonhatch** [catapult-project/catapult#4181] opened 2018-01-22 18:42 UTC
I checked this job: https://pinpoint-dot-chromeperf.appspot.com/job/129d0da8840000 and shouldn't the 2 points on the graph be at the same revision? This is a perf try job, so it should be HEAD and HEAD + patch right?

@dave-2

**Comment by dave-2** [comment] 2018-01-22 19:46
Duplicate of 4174

**Closed by dave-2** 2018-01-22 19:46 UTC
Labels: Bisect

**Comment by simonhatch** [comment] 2018-01-22 19:48
This issue is that they're actually different commits. Is that the same as #4174

**Comment by dave-2** [comment] 2018-01-22 20:16
Are you sure it is a perf try job? How was it kicked off? These commits are about 150 commits apart, and neither of them are recent. That's pretty typical of a bisect job.

**Comment by simonhatch** [comment] 2018-01-22 20:17
The extra test args.

But now I realize that this is dashboard initiated and it'll specify 2 different revisions, it's not HEAD and HEAD + patch.
