### ISSUE TITLE
Bisect jobs not finishing (but they are)

### ISSUE THREAD

**Issue by natorion** [catapult-project/catapult#2491] opened 2016-07-18 14:29 UTC
Please have a look at https://chromeperf.appspot.com/group_report?bug_id=625653. There are four bisect jobs and only the last one created a comment in the associated bug.

The really odd thing is that all of the jobs are started. For the older ones I would expect that they are completed but timed out.

Looking at the status pages of all the runs (e.g.https://chromeperf.appspot.com/buildbucket_job_status/9006812169392045296) it says status "COMPLETED".

**Comment by anniesullie** [comment] 2016-07-18 14:40
These bisects did fail. This is being investigated in #2476 and we're going to have an OKR around properly reporting the failures and reducing the failure rate. Closing this bug in favor of that one.

**Closed by anniesullie** 2016-07-18 14:40 UTC

**Comment by nickie** [comment] 2016-07-18 14:45
I'm not sure this is similar to #2476.  The report of the bisect job shows on  [bug's dashboard](https://chromeperf.appspot.com/group_report?bug_id=625653) but it does not seem to be complete:

```
chromium@402505 249.813 1.84519 5 good
chromium@402565 249.653 2.06674 5 good
chromium@402589 251.553 2.69795 5 good
chromium@402616 264.777 1.30233 5 bad
chromium@402737 264.746 2.2524 5 bad
```

What happened between 402589 and 402616?

**Comment by anniesullie** [comment] 2016-07-18 14:57
The problem is the same here and in #2476: the bisect job failed and the dashboard is not updating to show the failure in quicklog and in the bug. Here is what happened between 402589 and 402616:

From https://chromeperf.appspot.com/buildbucket_job_status/9006812169392045296:
`Status of the bisect job 9006812169392045296: COMPLETED, FAILURE`

And going to the linked bisect job:
https://build.chromium.org/p/tryserver.chromium.perf/builders/win_x64_perf_bisect/builds/1330/steps/Failure%20reason/logs/reason
`Infra Failure: Step('Working on revision chromium@402605.extract build') returned 1`

And indeed, if you go in and expand the steps for 402605, you'll see:
https://build.chromium.org/p/tryserver.chromium.perf/builders/win_x64_perf_bisect/builds/1330/steps/Working%20on%20revision%20chromium%40402605.extract%20build/logs/stdio
```

@@@STEP_NEST_LEVEL@1@@@
Set PYTHONPATH: C:\b\build\scripts;C:\b\build\site_config;C:\b\build\third_party;C:\b\build\third_party\buildbot_8_4p1;C:\b\build\third_party\buildbot_slave_8_4;C:\b\build\third_party\jinja2;C:\b\build\third_party\markupsafe;C:\b\build\third_party\mock-1.0.1;C:\b\build\third_party\coverage-3.7.1;C:\b\build\third_party\twisted_10_2;C:\b\build\third_party\requests_2_10_0;C:\b\build\third_party\sqlalchemy_0_7_1;C:\b\build\third_party\sqlalchemy_migrate_0_7_1;C:\b\build\third_party\tempita_0_5;C:\b\build\third_party\decorator_3_3_1;C:\b\build\third_party\setuptools-0.6c11;C:\b\build\third_party\httplib2\python2;C:\b\build\third_party\oauth2client;C:\b\build\third_party\uritemplate;C:\b\build\third_party\google_api_python_client;C:\b\build\third_party\site-packages;C:\b\build\scripts\tools;C:\b\build\scripts\release;C:\b\build_internal\site_config;C:\b\build_internal\symsrc;C:\b\build\slave;C:\b\build\slave\win_x64_perf_bisect\build;C:\b\depot_tools\python276_bin\python27.zip;C:\b\depot_tools\python276_bin\DLLs;C:\b\depot_tools\python276_bin\lib;C:\b\depot_tools\python276_bin\lib\plat-win;C:\b\depot_tools\python276_bin\lib\lib-tk;C:\b\depot_tools\python276_bin
Try 1: Fetching build from gs://chrome-perf/Win x64 Builder/full-build-win32_02602da5b8e5075e81ff0162262e0523fe4b1863.zip...

C:\b\depot_tools\python276_bin\python.exe C:\b\build\scripts\slave\.recipe_deps\depot_tools\gsutil.py cp "gs://chrome-perf/Win x64 Builder/full-build-win32_02602da5b8e5075e81ff0162262e0523fe4b1863.zip" file://.
Omitting prefix "gs://chrome-perf/Win x64 Builder/full-build-win32_02602da5b8e5075e81ff0162262e0523fe4b1863.zip/". (Did you mean to do cp -r?)
CommandException: No URLs matched
Try 2: Fetching build from gs://chrome-perf/Win x64 Builder/full-build-win32_02602da5b8e5075e81ff0162262e0523fe4b1863.zip...

C:\b\depot_tools\python276_bin\python.exe C:\b\build\scripts\slave\.recipe_deps\depot_tools\gsutil.py cp "gs://chrome-perf/Win x64 Builder/full-build-win32_02602da5b8e5075e81ff0162262e0523fe4b1863.zip" file://.
Omitting prefix "gs://chrome-perf/Win x64 Builder/full-build-win32_02602da5b8e5075e81ff0162262e0523fe4b1863.zip/". (Did you mean to do cp -r?)
CommandException: No URLs matched
Try 3: Fetching build from gs://chrome-perf/Win x64 Builder/full-build-win32_02602da5b8e5075e81ff0162262e0523fe4b1863.zip...

C:\b\depot_tools\python276_bin\python.exe C:\b\build\scripts\slave\.recipe_deps\depot_tools\gsutil.py cp "gs://chrome-perf/Win x64 Builder/full-build-win32_02602da5b8e5075e81ff0162262e0523fe4b1863.zip" file://.
Omitting prefix "gs://chrome-perf/Win x64 Builder/full-build-win32_02602da5b8e5075e81ff0162262e0523fe4b1863.zip/". (Did you mean to do cp -r?)
CommandException: No URLs matched
step returned non-zero exit code: 1
@@@STEP_EXCEPTION@@@
```

My guess is that Chrome can't be built at 402605. @ro-berto can you check?
