### ISSUE TITLE
Bisect stopped at V8 autoroll without descending

### ISSUE THREAD

**Issue by primiano** [catapult-project/catapult#3641] opened 2017-06-09 09:50 UTC
https://bugs.chromium.org/p/chromium/issues/detail?id=731059

Hi v8-autoroll@chromium.org, the bisect results pointed to your CL, please take a look at the
results.

**Comment by primiano** [comment] 2017-06-09 09:50
+@simonhatch, godfather of all bisects

**Comment by simonhatch** [comment] 2017-06-09 12:35
Duplicate of crbug.com/698254

**Closed by simonhatch** 2017-06-09 12:35 UTC
Labels: Bisect, Bug
