### ISSUE TITLE
Multiple failing pinpoint jobs

### ISSUE THREAD

**Issue by psmarshall** [catapult-project/catapult#4333] opened 2018-03-14 13:50 UTC
I'm getting a lot of failing pinpoint jobs, linked from these bugs:

https://bugs.chromium.org/p/chromium/issues/detail?id=820001
https://bugs.chromium.org/p/chromium/issues/detail?id=820002
https://bugs.chromium.org/p/chromium/issues/detail?id=820003
https://bugs.chromium.org/p/chromium/issues/detail?id=820017
https://bugs.chromium.org/p/chromium/issues/detail?id=820025

A bug was opened (https://github.com/catapult-project/catapult/issues/4323) for some of the failures, but closed. Is there a workaround or something? I can't really make much progress tracking down these regressions without the bisect.

**Comment by simonhatch** [comment] 2018-03-14 14:46
@dave-2

**Comment by simonhatch** [comment] 2018-03-14 14:58
Looks like a duplicate of #4323 , going to re-open that one.

**Closed by simonhatch** 2018-03-14 14:58 UTC
Labels: Bisect
