### ISSUE TITLE
Perf Dashboard: shift+click doesn't work anymore in checkboxes

### ISSUE THREAD

**Issue by phoglund** [catapult-project/catapult#1580] opened 2015-10-05 11:22 UTC
Chrome version: 45.0.2454.101 (Linux)
URL: https://chromeperf.appspot.com/alerts?sheriff=WebRTC%20Perf%20Sheriff&improvements=true

Please copy and paste any errors from JavaScript console (Ctrl+Shift+J to open):
Just two warnings:
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
core-overlay.html:348 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

Please describe the problem:
In https://chromeperf.appspot.com/alerts?sheriff=WebRTC%20Perf%20Sheriff&improvements=true, we often gets tons of alerts on the same revision. I would like to group them into the same bug. Since they don't coalesce into a single items like Chrome warnings for some reason, I like to shift-click on one alert and then on another further down the list to select all the alerts in between. This doesn't work. Sometimes only the two edge alerts are selected, sometimes random alerts from the list.

**Comment by anniesullie** [comment] 2015-10-05 13:47
@qyearsley @chrisphn

**Comment by qyearsley** [comment] 2015-10-05 17:23
Same as #1410 -- I actually noticed this several months ago, but nobody else has complained about it until now, so it wasn't a priority. If I can figure out the cause of this I'll be super happy.

Closing, since this issue can be tracked in #1410.

**Closed by qyearsley** 2015-10-05 17:23 UTC
Labels: Perf Dashboard
