### ISSUE TITLE
Do not use "point id" where "commit position" would be more appropriate

### ISSUE THREAD

**Issue by perezju** [catapult-project/catapult#3014] opened 2016-11-17 10:27 UTC
**Context:** The dashboard requires a *point id*, a monotonically increasing integer, to uniquely identify builds and sort them in the correct order e.g. in graphs. In most places the *chromium commit position* fulfills this role. On internal builds, however, the commit position does not uniquely identify builds and, thus, unix time stamps are used there as point ids instead.

**Problem:** In many places, particularly for display, point ids are being used where instead showing a commit position would be a lot more natural and useful.

Examples:

* Titles of bugs created from the dashboard: [1.8% regression in system_health.memory_mobile at 1477566183:1477588743](https://bugs.chromium.org/p/chromium/issues/detail?id=661495). Identifying the range instead as 427884:427987, even if not strictly speaking accurate, would be a lot more useful.

* Triage page for alerts:

  ![atujqfqrq0j](https://cloud.githubusercontent.com/assets/16922344/20385571/d00d736a-acaf-11e6-80d2-388a3c1ffb5b.png)

  Here too, using commit position ranges both for display *and* computations for alert grouping would be a lot more useful.

@anniesullie

**Comment by anniesullie** [comment] 2016-11-18 22:55
@eakuefner @jessimb because this would be a big improvement to sheriffing for downstream Android; we should slot this into the work @jessimb is doing in that direction.

Some technical notes:
We already have `a_default_rev` on the `Row` entity which controls which revision shows up in the x-axis of the chart. I think it is a bug that `a_default_rev` is not the display revision on the alerts table and the revision used for the bug.

So on top of fixing the above issues, we could also use `a_default_rev` as a revision to use for comparing overlapping.

But there is a problem here: `a_default_rev` for downstream Android is the git revision for downstream. And we ideally want overlapping chromium commit positions. We can't really do overlapping revisions for git commits because we don't have any ordering information anyway. @perezju : I think we would want to either change `a_default_rev` for downstream to the chromium commit pos, or introduce a second concept for overlapping revisions that's different from the display revisions. Opinions on this?

**Comment by perezju** [comment] 2016-11-21 09:42
I think setting `a_default_rev` to `r_commit_pos` for downstream and using it for display and overlap calculations would be a huge improvement. It also does sound to me like a neat and clean solution.

For overlap computation I think this is the best we can do, and introducing any further complexity (e.g. trying to properly sort git hashes) would only give us more headaches and very little in return.

**[nit]** For display, the only downside of only showing commit positions is that it hides a bit the fact that they do not uniquely identify a change anymore. On the [health dashboard](https://chrome-health.googleplex.com/health-plan/android-chrome/memory/nexus5/) I try to attenuate this issue by showing `"{commit_pos}-{first_three_chars_of_clank_hash}"`. Still not perfect (I've seen collisions even with that scheme), but still a bit more informative.

Anyway, even if we do not implement my "nit" above, just showing the commit position is already way better that using the time stamp, which tells us next to nothing and can be often misleading.

**Comment by benhenry** [comment] 2016-11-21 17:32
Naively, could we adjust how we compute build/CL ranges by using Git hash
nomenclature instead of monotonically increasing numbers - which are
completely artificial and arbitrary on trunk?

**Comment by anniesullie** [comment] 2016-11-22 14:37
@benhenry - We currently don't have any way to do definitive ordering of git hashes. So as @perezju says, this would add a lot of complexity in code that computes overlaps and such. I think commit positions solve our problems without adding too much complexity.

**Comment by jessimb** [comment] 2017-02-16 17:51
Downstream Anomalies from now on will have a 'display_start' and 'display_end' that the alerts-table will look for when displaying revision ranges. We kept a_default_rev to be the same because the clank hash is needed for bisect. We now check directly for the master name and add display_start/end if appropriate. It was the simplest way to fix the issue and not accumulate much more data. 

So be on the lookout for 'ClankInternal' masters with Chromium commit positions!

**Comment by jessimb** [comment] 2017-02-17 19:30
Hm. It seems like new alerts don't have the correct display rev. This could potentially be due to the test kind? We now check for ```test.master_name == 'ClankInternal'``` so if the test passed into ProcessTest isn't a ```TestMetadata```, it won't properly check the master. As far as I can tell, it really should be a ```TestMetadata```. Anyone have thoughts on why it didn't work as intended? @anniesullie

**Comment by anniesullie** [comment] 2017-02-23 17:08
Sorry for the delayed response! Can you give an example alert with the wrong display rev?

**Comment by jessimb** [comment] 2017-02-23 17:18
[These alerts](https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgIDgxK76qAoM) show point id/timestamp instead of display revisions. In the datastore, their display_start/end are 'null'.

**Comment by anniesullie** [comment] 2017-09-08 15:18
Assigning to Ben since IIUC he's planning to look into this.

**Comment by benshayden** [comment] 2018-01-31 00:46
The initial report from perezju above mentions 2 examples of problems caused by the point id concept. @tdresser and Pete Williamson (Is Pete on github?) recently reported another problem that I think is caused by the same underlying point id confusion: [Mixing ChromiumPerf and internal charts in a single report](https://chromeperf.appspot.com/report?sid=e3f57fcde3c8068da8df9ccc3d31aa74df269b989ad5be1a17ca4a4e8314bcef&start_rev=1514619301&end_rev=1515402206) can cause some charts to incorrectly display "No data available".
These are all bad bugs, no doubt, and please correct me if I'm wrong, but it sounds like they don't totally prevent you from using the dashboard. If you can work around them for now, then I'll experiment with some approaches to solving it in the context of the V2 SPA frontend rewrite.

**Comment by perezju** [comment] 2018-01-31 10:03
We've lived with this for so long. I think we're happy to wait a little longer for a good solid solution 😄

**Closed** 2018-06-04 18:58 UTC
Labels: Perf Dashboard
