### ISSUE TITLE
Don't read the whole trace file into memory

### ISSUE THREAD

**Issue by chiniforooshan** [catapult-project/catapult#1307] opened 2015-08-21 15:22 UTC
Trace files with V8 samples easily get too large for the model importer making it fail due to lack of memory.

Verify that the V8 samples consume most of the memory. If they do, probably a low hanging fruit to easily improve the situation is to fuse consequent identical samples into one sample (with proper start, end, and weight) in the in-memory model.

**Comment by randomascii** [comment] 2015-08-21 22:40
Instead of fusing adjacent samples can we merge all matching samples? Assuming that these samples include call stacks we could have a hash table with the index being a call stack and the payload being either a count or a list of sample times.

If the leaf address varies too much then we could hash the stack not including the leaf address and have the payload be a list of addresses within the leaf function together with the sample time.

This increases the CPU overhead somewhat, but this technique can reduce the memory consumption enough that overall performance may actually not be affected.

**Comment by chiniforooshan** [comment] 2015-08-31 15:34
I doubt if that would help much. I think we don't keep the whole stack trace for each sample. We keep stack frames in a graph with parent/child relationships as edges and for every sample we just keep a pointer to the leaf stack frame in that graph (the whole stack trace can be obtained by following the parent links).

I took a quick look at an example trace. It had ~65K samples and ~8K stack frames. Merging consequent "identical" samples would reduce the number of samples to ~15K. How about I implement this for now, since it's very simple and reduces the sample size by 80%, and we can come back and consider more complicated compression methods later?

**Comment by dj2** [comment] 2015-08-31 15:58
There isn't much we can do about this on the trace-viewer side. We'd have to modify the v8 sampler to do the collapsing for us which is a bigger issue. That code is written and currently maintained by the devtools folks.

The trace data always comes into tracing as a single large string which is the issue that is being run into. We don't have the ability to take it as chunks or stream the data and we'd need to make changes into chrome and tracing to make that happen which is also a large, hard project.

I don't think there is much we can do about this in the short term.

**Comment by dj2** [comment] 2015-08-31 16:38
Closing as a dupe of #627.

**Closed by dj2** 2015-08-31 16:38 UTC

**Comment by natduca** [comment] 2015-09-16 01:51
I'm confused why we're duping this... are we having real crashes with reasonable traces?

**Comment by chiniforooshan** [comment] 2015-09-16 14:45
Depends on what is considered reasonable :) I originally opened the issue when I tried to import a trace file with V8 samples of 1 minute interaction with sfgate.
